export type SystemTemplatePreferredStorage = 'WORD_ONLINE' | 'GOOGLE_DOCS';

export type SystemTemplateSeed = {
  systemKey: string;
  title: string;
  description?: string;
  tags?: string[];
  preferredStorage?: SystemTemplatePreferredStorage;
  content: string;
  metadata?: Record<string, any>;
};

const join = (parts: string[]) => parts.join('\n');

const vlWrap = (parts: string[]) =>
  join([
    `<div style="font-family: Calibri, Arial, sans-serif; font-size: 11pt; line-height: 1.35; color: #0f172a;">`,
    ...parts,
    `</div>`,
  ]);

const vlTitle = (title: string) =>
  `<h1 style="text-align:center; margin: 0 0 10px 0; font-size: 20pt; color: #111827; letter-spacing: 0.5px;">${title}</h1>`;

const vlSubtitle = (subtitle: string) =>
  `<p style="text-align:center; margin: 0 0 14px 0; font-size: 10.5pt; color: #475569;">${subtitle}</p>`;

const vlSection = (title: string) =>
  `<h2 style="margin: 18px 0 8px 0; font-size: 13.5pt; color: #111827; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px;">${title}</h2>`;

const vlFill = (label: string) =>
  `<span style="background-color: #FEF3C7; border: 1px solid #FCD34D; color: #92400E; border-radius: 4px; padding: 1px 6px; font-weight: 700;">${label}</span>`;

const vlInfoTable = (partyLabel: string, opposingLabel: string) => `
<table style="width: 100%; border-collapse: collapse; border: 1px solid #CBD5E1; background: #F8FAFC; margin: 10px 0 14px 0;">
  <tr>
    <td style="border: 1px solid #CBD5E1; padding: 8px; width: 25%;"><strong>CNJ</strong><br/>{{process.cnj}}</td>
    <td style="border: 1px solid #CBD5E1; padding: 8px; width: 25%;"><strong>Vara</strong><br/>{{process.vars}}</td>
    <td style="border: 1px solid #CBD5E1; padding: 8px; width: 25%;"><strong>Comarca</strong><br/>{{process.district}}</td>
    <td style="border: 1px solid #CBD5E1; padding: 8px; width: 25%;"><strong>Tribunal</strong><br/>{{process.court}}</td>
  </tr>
  <tr>
    <td style="border: 1px solid #CBD5E1; padding: 8px;"><strong>${partyLabel}</strong><br/>{{contact.name}}</td>
    <td style="border: 1px solid #CBD5E1; padding: 8px;"><strong>${opposingLabel}</strong><br/>{{opposing.name}}</td>
    <td style="border: 1px solid #CBD5E1; padding: 8px;"><strong>Valor</strong><br/>{{process.value}}</td>
    <td style="border: 1px solid #CBD5E1; padding: 8px;"><strong>Status</strong><br/>{{process.status}}</td>
  </tr>
</table>
`.trim();

const vlSignature = (label: string) =>
  join([
    `<p style="margin-top: 22px;">${vlFill('LOCAL')}, {{today.fullDate}}.</p>`,
    `<p style="margin-top: 22px;">________________________________________</p>`,
    `<p style="margin: 0;"><strong>${label}:</strong> {{user.name}}</p>`,
    `<p style="margin: 0;"><strong>OAB:</strong> {{user.oab}} ${vlFill('PREENCHER OAB SE NECESSÁRIO')}</p>`,
  ]);

type VlTone = 'info' | 'warn' | 'success';

const VL_TONES: Record<VlTone, { bg: string; border: string; title: string }> = {
  info: { bg: '#EEF2FF', border: '#C7D2FE', title: '#1E3A8A' },
  warn: { bg: '#FFFBEB', border: '#FDE68A', title: '#92400E' },
  success: { bg: '#ECFDF5', border: '#A7F3D0', title: '#065F46' },
};

const vlCard = (title: string, bullets: string[], tone: VlTone = 'info') => {
  const palette = VL_TONES[tone];
  const list = bullets
    .map((b) => `<li style="margin: 4px 0;">${b}</li>`)
    .join('');

  return `
<table style="width: 100%; border-collapse: collapse; border: 1px solid ${palette.border}; background: ${palette.bg}; margin: 10px 0 14px 0;">
  <tr>
    <td style="padding: 10px;">
      <div style="font-weight: 800; color: ${palette.title}; margin-bottom: 6px;">${title}</div>
      <ul style="margin: 0 0 0 18px; padding: 0;">
        ${list}
      </ul>
    </td>
  </tr>
</table>
`.trim();
};

const civilIntro = (
  partyLabel: string,
  opposingLabel: string,
  baseLegal: string[],
  checklist: string[],
) => [
  vlInfoTable(partyLabel, opposingLabel),
  vlCard('Base legal (CPC) — lembretes', baseLegal, 'info'),
  vlCard('Checklist rápido (antes de protocolar)', checklist, 'warn'),
];

export const SYSTEM_TEMPLATE_SEEDS: SystemTemplateSeed[] = [
  {
    systemKey: 'PROCURACAO_GERAL',
    title: 'Procuração (Geral)',
    description:
      'Modelo padrão de procuração. Ajuste poderes específicos conforme o caso e a praxe local.',
    tags: ['Procuração', 'Sistema'],
    preferredStorage: 'WORD_ONLINE',
    content: join([
      `<h1 style="text-align:center;">PROCURAÇÃO</h1>`,
      `<p><strong>OUTORGANTE:</strong> {{contact.name}}, CPF/CNPJ {{contact.document}}, endereço {{contact.address.full}}.</p>`,
      `<p><strong>OUTORGADO(S):</strong> {{user.name}}, advogado(a), OAB {{user.oab}}.</p>`,
      `<p><strong>PODERES:</strong> confere poderes para o foro em geral, com cláusula <em>ad judicia</em> e <em>ad extra</em>, podendo praticar todos os atos necessários ao fiel cumprimento do mandato.</p>`,
      `<p>{{current.city}}, {{today.fullDate}}.</p>`,
      `<p>________________________________________</p>`,
      `<p>{{contact.name}}</p>`,
    ]),
    metadata: {
      sections: [{ title: 'Poderes', help: 'Confirme poderes especiais quando necessário.' }],
      internalComments: ['Verificar se precisa de poderes especiais (receber, dar quitação, transigir).'],
      blocks: [{ id: 'b_poderes', type: 'subtitle', title: 'Poderes' }],
    },
  },
  {
    systemKey: 'PETICAO_INICIAL_GENERIC',
    title: 'Petição Inicial (Genérica)',
    description: 'Baseada no Art. 319 do CPC. Use para ações de rito comum.',
    tags: ['Cível', 'CPC', 'Petição', 'Sistema'],
    preferredStorage: 'WORD_ONLINE',
    content: join([
      `<h1 style="text-align:center;">PETIÇÃO INICIAL</h1>`,
      `<p><strong>Processo nº:</strong> {{process.cnj}}</p>`,
      `<p><strong>Excelentíssimo(a) Senhor(a) Doutor(a) Juiz(a) de Direito</strong></p>`,
      `<p>{{process.vars}} Vara - {{process.district}}/{{process.uf}}</p>`,
      `<hr/>`,
      `<p><strong>{{contact.name}}</strong>, CPF/CNPJ {{contact.document}}, e-mail {{contact.email}}, telefone {{contact.phone}}, endereço {{contact.address.full}}, vem, por seu advogado, propor a presente ação em face de <strong>{{opposing.name}}</strong>, CPF/CNPJ {{opposing.document}}, endereço {{opposing.address.full}}, pelos fatos e fundamentos a seguir.</p>`,
      `<h2>Dos Fatos</h2>`,
      `<p>{{DOS_FATOS}}</p>`,
      `<h2>Do Direito</h2>`,
      `<p>{{DO_DIREITO}}</p>`,
      `<h2>Dos Pedidos</h2>`,
      `<ol><li>{{PEDIDO_1}}</li><li>{{PEDIDO_2}}</li><li>{{PEDIDO_3}}</li></ol>`,
      `<p><strong>Valor da causa:</strong> {{process.value}}</p>`,
      `<p>{{current.city}}, {{today.fullDate}}.</p>`,
      `<p>________________________________________</p>`,
      `<p>{{user.name}}<br/>OAB: {{user.oab}}</p>`,
    ]),
    metadata: {
      sections: [
        { title: 'Dos Fatos', help: 'Descreva o ocorrido com clareza e cronologia.' },
        { title: 'Do Direito', help: 'Fundamente com base legal e jurisprudência aplicável.' },
        { title: 'Dos Pedidos', help: 'Liste pedidos de forma objetiva e numerada.' },
      ],
      internalComments: ['Verificar pedido de Justiça Gratuita', 'Checar competência e valor da causa'],
      blocks: [
        { id: 'b_fatos', type: 'subtitle', title: 'Dos Fatos' },
        { id: 'b_direito', type: 'subtitle', title: 'Do Direito' },
        { id: 'b_pedidos', type: 'subtitle', title: 'Dos Pedidos' },
        { id: 'b_jg', type: 'textBox', title: 'Justiça Gratuita', help: 'Marcar se cabível, anexar documentos.' },
      ],
    },
  },
  {
    systemKey: 'CONTESTACAO_GENERIC',
    title: 'Contestação (Genérica)',
    description: 'Estrutura base de contestação (CPC). Ajuste preliminares e mérito conforme o caso.',
    tags: ['Cível', 'CPC', 'Contestação', 'Sistema'],
    preferredStorage: 'WORD_ONLINE',
    content: join([
      `<h1 style="text-align:center;">CONTESTAÇÃO</h1>`,
      `<p><strong>Processo nº:</strong> {{process.cnj}}</p>`,
      `<p><strong>Excelentíssimo(a) Senhor(a) Doutor(a) Juiz(a) de Direito</strong></p>`,
      `<p>{{process.vars}} Vara - {{process.district}}/{{process.uf}}</p>`,
      `<hr/>`,
      `<p><strong>{{contact.name}}</strong>, já qualificado(a), por seu advogado, apresenta CONTESTAÇÃO à ação proposta por <strong>{{opposing.name}}</strong>, pelos fundamentos a seguir.</p>`,
      `<h2>Preliminares</h2>`,
      `<p>{{PRELIMINARES}}</p>`,
      `<h2>Mérito</h2>`,
      `<p>{{MERITO}}</p>`,
      `<h2>Pedidos</h2>`,
      `<ol><li>{{PEDIDO_1}}</li><li>{{PEDIDO_2}}</li></ol>`,
      `<p>{{current.city}}, {{today.fullDate}}.</p>`,
      `<p>________________________________________</p>`,
      `<p>{{user.name}}<br/>OAB: {{user.oab}}</p>`,
    ]),
    metadata: {
      sections: [
        { title: 'Preliminares', help: 'Liste preliminares e matérias processuais pertinentes.' },
        { title: 'Mérito', help: 'Enfrente fatos e direito; impugne documentos e alegações.' },
      ],
      internalComments: ['Checar prazo de contestação', 'Verificar necessidade de reconvenção'],
      blocks: [
        { id: 'b_prelim', type: 'subtitle', title: 'Preliminares' },
        { id: 'b_merito', type: 'subtitle', title: 'Mérito' },
      ],
    },
  },
  {
    systemKey: 'DECLARACAO_HIPOSSUFICIENCIA',
    title: 'Declaração de Hipossuficiência',
    description: 'Declaração para fins de justiça gratuita. Ajuste conforme o caso concreto.',
    tags: ['Justiça Gratuita', 'CPC', 'Sistema'],
    preferredStorage: 'WORD_ONLINE',
    content: join([
      `<h1 style="text-align:center;">DECLARAÇÃO DE HIPOSSUFICIÊNCIA</h1>`,
      `<p>Eu, <strong>{{contact.name}}</strong>, CPF/CNPJ {{contact.document}}, residente e domiciliado(a) em {{contact.address.full}}, DECLARO, para os devidos fins, que não possuo condições de arcar com as custas processuais e honorários advocatícios sem prejuízo do meu sustento e de minha família.</p>`,
      `<p>Declaro, ainda, estar ciente das penas da lei em caso de falsidade.</p>`,
      `<p>{{current.city}}, {{today.fullDate}}.</p>`,
      `<p>________________________________________</p>`,
      `<p>{{contact.name}}</p>`,
    ]),
    metadata: {
      sections: [{ title: 'Declaração', help: 'Confirme a necessidade de justiça gratuita.' }],
      internalComments: ['Verificar documentos de renda antes de anexar.'],
      blocks: [{ id: 'b_decl', type: 'textBox', title: 'Observações', help: 'Notas internas do escritório.' }],
    },
  },
  {
    systemKey: 'CIVIL_INICIAL',
    title: 'INICIAL',
    description:
      'Petição inicial cível (rito comum), com quadro-resumo e checklist. Ajuste conforme o caso concreto (CPC, art. 319).',
    tags: ['Cível', 'CPC', 'Inicial', 'Sistema'],
    preferredStorage: 'WORD_ONLINE',
    content: vlWrap([
      vlTitle('PETIÇÃO INICIAL'),
      vlSubtitle('Visual Law • Estrutura CPC (art. 319) • Quadro-resumo + pedidos objetivos'),
      ...civilIntro(
        'REQUERENTE (autor)',
        'REQUERIDO (réu)',
        [
          'Art. 319 (requisitos da inicial)',
          'Art. 320 (documentos indispensáveis)',
          'Art. 330 (inépcia/indeferimento)',
          'Art. 300 (tutela de urgência, se cabível)',
          'Art. 85 (honorários)',
        ],
        [
          'Competência/foro e endereçamento revisados',
          'Qualificação completa das partes (inclusive endereços)',
          'Fatos em cronologia + prova vinculada',
          'Pedidos numerados e executáveis',
          'Valor da causa conferido (art. 292)',
        ],
      ),
      `<p><strong>Excelentíssimo(a) Senhor(a) Doutor(a) Juiz(a) de Direito</strong></p>`,
      `<p>${vlFill('PREENCHER: JUÍZO/COMPETÊNCIA')}<br/><span style="color:#64748b;">Sugestão:</span> {{process.vars}} • {{process.district}}</p>`,
      `<hr/>`,
      `<p><strong>{{contact.name}}</strong>, CPF/CNPJ {{contact.document}}, e-mail {{contact.email}}, telefone {{contact.phone}}, endereço {{contact.address.full}}, por seu advogado ({{user.name}}), vem propor a presente ação em face de <strong>{{opposing.name}}</strong>, CPF/CNPJ {{opposing.document}}, endereço {{opposing.address.full}}, pelos fatos e fundamentos a seguir.</p>`,
      vlSection('1. Síntese do caso (1 página)'),
      `<table style="width:100%; border-collapse:collapse; border:1px solid #E2E8F0; background:#FFFFFF; margin: 8px 0;">`,
      `<tr>`,
      `<td style="border:1px solid #E2E8F0; padding:10px; width:33%; vertical-align:top;"><strong>O que aconteceu</strong><br/>${vlFill('PREENCHER EM 3–6 LINHAS')}</td>`,
      `<td style="border:1px solid #E2E8F0; padding:10px; width:33%; vertical-align:top;"><strong>Provas-chave</strong><br/>${vlFill('LISTAR DOCS')}</td>`,
      `<td style="border:1px solid #E2E8F0; padding:10px; width:33%; vertical-align:top;"><strong>O que se pede</strong><br/>${vlFill('PEDIDOS (2–5 ITENS)')}</td>`,
      `</tr>`,
      `</table>`,
      vlSection('2. Dos fatos (cronologia)'),
      `<p>${vlFill('PREENCHER: narrativa completa e cronológica')}</p>`,
      vlSection('3. Do direito (fundamentos)'),
      `<p>${vlFill('PREENCHER: base legal + jurisprudência + aplicação ao caso')}</p>`,
      vlSection('4. Tutela de urgência (se cabível)'),
      `<p>${vlFill('PREENCHER: probabilidade do direito + perigo de dano + reversibilidade')}</p>`,
      vlSection('5. Dos pedidos (objetivos e numerados)'),
      `<ol>`,
      `<li>${vlFill('PREENCHER: pedido principal')}</li>`,
      `<li>${vlFill('PREENCHER: pedido subsidiário/alternativo (se houver)')}</li>`,
      `<li>${vlFill('PREENCHER: custas e honorários (art. 85, CPC)')}</li>`,
      `</ol>`,
      vlSection('6. Provas e requerimentos finais'),
      `<p>Protesta por todos os meios de prova em direito admitidos, especialmente ${vlFill('documental/testemunhal/pericial')}.</p>`,
      `<p>Requer a citação da parte requerida para, querendo, contestar, sob pena de revelia, e ao final a procedência dos pedidos.</p>`,
      `<p><strong>Valor da causa:</strong> {{process.value}} ${vlFill('CONFERIR/ATUALIZAR')}</p>`,
      vlSignature('Advogado(a)'),
    ]),
    metadata: {
      sections: [
        { title: 'Síntese do caso', help: 'Resumo de 1 página: fato + prova + pedido.' },
        { title: 'Fatos', help: 'Cronologia com datas e eventos verificáveis.' },
        { title: 'Direito', help: 'Base legal e jurisprudência pertinente.' },
        { title: 'Pedidos', help: 'Pedidos numerados, claros e executáveis.' },
      ],
      internalComments: [
        'Checar competência/foro e endereçamento.',
        'Avaliar Justiça Gratuita e anexos.',
        'Conferir valor da causa e tutela (se cabível).',
      ],
      blocks: [
        { id: 'b_quadro_resumo', type: 'table', title: 'Quadro-resumo' },
        { id: 'b_cronologia', type: 'list', title: 'Cronologia (fatos)' },
        { id: 'b_pedidos', type: 'list', title: 'Pedidos' },
      ],
    },
  },
  {
    systemKey: 'CIVIL_EMENDA_INICIAL',
    title: 'EMENDA À INICIAL',
    description: 'Emenda à inicial para cumprimento de despacho (CPC, art. 321).',
    tags: ['Cível', 'CPC', 'Emenda', 'Sistema'],
    preferredStorage: 'WORD_ONLINE',
    content: vlWrap([
      vlTitle('EMENDA À INICIAL'),
      vlSubtitle('Cumprimento de despacho • Ajustes objetivos • Checklist'),
      ...civilIntro(
        'REQUERENTE (autor)',
        'REQUERIDO (réu)',
        ['Art. 321 (emenda da inicial)', 'Art. 319 (requisitos)', 'Art. 320 (documentos)', 'Art. 292 (valor da causa)'],
        [
          'Itens do despacho listados (um a um)',
          'Correções aplicadas conforme determinação',
          'Documentos anexados e descritos (tabela/rol)',
          'Valor da causa conferido e justificado (se necessário)',
          'Pedido final de prosseguimento claro',
        ],
      ),
      `<p><strong>Excelentíssimo(a) Senhor(a) Doutor(a) Juiz(a) de Direito</strong></p>`,
      `<p>${vlFill('PREENCHER: JUÍZO/VARA')}<br/><span style="color:#64748b;">Sugestão:</span> {{process.vars}} • {{process.district}}</p>`,
      `<hr/>`,
      `<p><strong>{{contact.name}}</strong>, já qualificado(a), em atenção ao despacho de ${vlFill('PREENCHER: DATA/ID')}, apresenta <strong>EMENDA À INICIAL</strong>, nos termos do art. 321 do CPC.</p>`,
      vlSection('1. O que foi determinado'),
      `<p>${vlFill('PREENCHER: itens do despacho')}</p>`,
      vlSection('2. Cumprimento (item a item)'),
      `<ol>`,
      `<li><strong>Qualificação/endereços:</strong> ${vlFill('PREENCHER')}</li>`,
      `<li><strong>Documentos:</strong> ${vlFill('PREENCHER: listar anexos e finalidade')}</li>`,
      `<li><strong>Pedidos/causa de pedir:</strong> ${vlFill('PREENCHER')}</li>`,
      `<li><strong>Valor da causa:</strong> ${vlFill('PREENCHER')}</li>`,
      `</ol>`,
      vlSection('3. Requerimentos'),
      `<p>Requer o recebimento da emenda e o regular prosseguimento do feito.</p>`,
      vlSignature('Advogado(a)'),
    ]),
    metadata: {
      sections: [
        { title: 'Determinações', help: 'Liste itens do despacho para conferir cumprimento.' },
        { title: 'Cumprimento', help: 'Responda item a item, com objetividade.' },
      ],
      internalComments: ['Conferir prazo para emenda.', 'Checar aditamento de pedidos/valor da causa.'],
      blocks: [{ id: 'b_emenda', type: 'list', title: 'Checklist' }],
    },
  },
  {
    systemKey: 'CIVIL_CONTESTACAO',
    title: 'CONTESTAÇÃO',
    description: 'Contestação cível com preliminares (art. 337) e mérito.',
    tags: ['Cível', 'CPC', 'Contestação', 'Sistema'],
    preferredStorage: 'WORD_ONLINE',
    content: vlWrap([
      vlTitle('CONTESTAÇÃO'),
      vlSubtitle('Preliminares (art. 337) • Mérito • Provas • Pedidos'),
      ...civilIntro(
        'REQUERIDO (réu)',
        'REQUERENTE (autor)',
        [
          'Art. 335 (prazo de contestação)',
          'Art. 337 (preliminares)',
          'Art. 341 (impugnação específica)',
          'Art. 373 (ônus da prova)',
          'Art. 85 (honorários)',
        ],
        [
          'Prazo e tempestividade conferidos',
          'Preliminares (se houver) selecionadas e provadas',
          'Impugnação específica de fatos e documentos (por itens)',
          'Pedidos finais adequados (improcedência/acolhimento preliminar)',
          'Provas requeridas (rol/quesitos/assistente, se cabível)',
        ],
      ),
      `<p><strong>Excelentíssimo(a) Senhor(a) Doutor(a) Juiz(a) de Direito</strong></p>`,
      `<p>${vlFill('PREENCHER: JUÍZO/VARA')}<br/><span style="color:#64748b;">Sugestão:</span> {{process.vars}} • {{process.district}}</p>`,
      `<hr/>`,
      `<p><strong>{{contact.name}}</strong>, já qualificado(a), apresenta <strong>CONTESTAÇÃO</strong> à ação proposta por <strong>{{opposing.name}}</strong>.</p>`,
      vlSection('1. Quadro-resumo (tese em bullets)'),
      `<ul>`,
      `<li><strong>Tese principal:</strong> ${vlFill('PREENCHER EM 1 FRASE')}</li>`,
      `<li><strong>Fatos controvertidos:</strong> ${vlFill('PREENCHER')}</li>`,
      `<li><strong>Provas:</strong> ${vlFill('PREENCHER')}</li>`,
      `</ul>`,
      vlSection('2. Preliminares (CPC, art. 337)'),
      `<p>${vlFill('PREENCHER: preliminares cabíveis + fundamentos')}</p>`,
      `<table style="width:100%; border-collapse:collapse; border:1px solid #E2E8F0; background:#FFFFFF;">`,
      `<tr><td style="border:1px solid #E2E8F0; padding:10px; width:50%;">☐ Incompetência<br/>☐ Ilegitimidade<br/>☐ Litispendência<br/>☐ Coisa julgada</td>`,
      `<td style="border:1px solid #E2E8F0; padding:10px; width:50%;">☐ Prescrição/Decadência<br/>☐ Inépcia<br/>☐ Falta de interesse<br/>☐ Outras</td></tr>`,
      `</table>`,
      vlSection('3. Mérito (impugnação específica)'),
      `<p>${vlFill('PREENCHER: impugnar fatos, documentos e pedidos')}</p>`,
      vlSection('4. Provas'),
      `<p>Requer produção de provas: ${vlFill('documental/testemunhal/pericial/depoimento pessoal')}.</p>`,
      vlSection('5. Pedidos'),
      `<ol>`,
      `<li>${vlFill('PREENCHER: acolhimento das preliminares (se houver)')}</li>`,
      `<li>${vlFill('PREENCHER: improcedência dos pedidos')}</li>`,
      `<li>Custas e honorários (art. 85, CPC).</li>`,
      `</ol>`,
      vlSignature('Advogado(a)'),
    ]),
    metadata: {
      sections: [
        { title: 'Preliminares', help: 'Art. 337: selecione só o aplicável e prove.' },
        { title: 'Mérito', help: 'Impugnação específica: fatos e documentos.' },
      ],
      internalComments: ['Checar prazo de contestação', 'Avaliar reconvenção'],
      blocks: [{ id: 'b_prelim', type: 'checklist', title: 'Preliminares (art. 337)' }],
    },
  },
  {
    systemKey: 'CIVIL_RECONVENCAO',
    title: 'RECONVENÇÃO',
    description: 'Reconvenção com fatos, direito, pedidos e valor da causa próprio.',
    tags: ['Cível', 'CPC', 'Reconvenção', 'Sistema'],
    preferredStorage: 'WORD_ONLINE',
    content: vlWrap([
      vlTitle('RECONVENÇÃO'),
      vlSubtitle('Pedido autônomo do réu contra o autor • Valor da causa próprio'),
      ...civilIntro(
        'RECONVINTE (réu)',
        'RECONVINDO (autor)',
        ['Art. 343 (reconvenção)', 'Art. 319 (requisitos)', 'Art. 320 (documentos)', 'Art. 292 (valor da causa)', 'Art. 85 (honorários)'],
        [
          'Conexão/cabimento explicado com clareza',
          'Causa de pedir autônoma e bem delimitada',
          'Pedidos claros e executáveis (numerados)',
          'Valor da causa da reconvenção definido e coerente',
          'Provas e documentos vinculados aos fatos',
        ],
      ),
      `<p><strong>Excelentíssimo(a) Senhor(a) Doutor(a) Juiz(a) de Direito</strong></p>`,
      `<p>${vlFill('PREENCHER: JUÍZO/VARA')}<br/><span style="color:#64748b;">Sugestão:</span> {{process.vars}} • {{process.district}}</p>`,
      `<hr/>`,
      `<p><strong>{{contact.name}}</strong>, apresenta <strong>RECONVENÇÃO</strong> em face de <strong>{{opposing.name}}</strong>.</p>`,
      vlSection('1. Cabimento e conexão'),
      `<p>${vlFill('PREENCHER')}</p>`,
      vlSection('2. Fatos'),
      `<p>${vlFill('PREENCHER')}</p>`,
      vlSection('3. Direito'),
      `<p>${vlFill('PREENCHER')}</p>`,
      vlSection('4. Pedidos'),
      `<ol>`,
      `<li>${vlFill('PREENCHER: pedido principal')}</li>`,
      `<li>${vlFill('PREENCHER: pedido subsidiário/alternativo')}</li>`,
      `</ol>`,
      `<p><strong>Valor da causa (reconvenção):</strong> ${vlFill('PREENCHER/ATUALIZAR')}</p>`,
      vlSignature('Advogado(a)'),
    ]),
    metadata: {
      sections: [
        { title: 'Cabimento', help: 'Explique conexão e adequação.' },
        { title: 'Pedidos', help: 'Pedidos claros + valor da causa próprio.' },
      ],
      internalComments: ['Verificar custas da reconvenção', 'Checar rito/competência'],
      blocks: [{ id: 'b_reconv', type: 'textBox', title: 'Valor da causa (reconvenção)' }],
    },
  },
  {
    systemKey: 'CIVIL_REPLICA',
    title: 'RÉPLICA',
    description: 'Réplica à contestação: impugna preliminares, mérito e documentos; requer provas.',
    tags: ['Cível', 'CPC', 'Réplica', 'Sistema'],
    preferredStorage: 'WORD_ONLINE',
    content: vlWrap([
      vlTitle('RÉPLICA'),
      vlSubtitle('Impugna preliminares, mérito e documentos • Requer provas'),
      ...civilIntro(
        'AUTOR (requerente)',
        'RÉU (requerido)',
        ['Art. 350 (impugnação da contestação)', 'Art. 351 (fatos impeditivos/modificativos/extintivos)', 'Art. 434/435 (documentos)', 'Art. 373 (ônus da prova)'],
        [
          'Preliminares rebatidas (se houver)',
          'Mérito rebatido por itens (tese x prova)',
          'Documentos impugnados e diligências requeridas',
          'Provas especificadas (se necessário)',
          'Reiteração dos pedidos iniciais',
        ],
      ),
      `<p><strong>Excelentíssimo(a) Senhor(a) Doutor(a) Juiz(a) de Direito</strong></p>`,
      `<p>${vlFill('PREENCHER: JUÍZO/VARA')}<br/><span style="color:#64748b;">Sugestão:</span> {{process.vars}} • {{process.district}}</p>`,
      `<hr/>`,
      `<p><strong>{{contact.name}}</strong>, vem apresentar <strong>RÉPLICA</strong> à contestação de <strong>{{opposing.name}}</strong>.</p>`,
      vlSection('1. Impugnação às preliminares'),
      `<p>${vlFill('PREENCHER')}</p>`,
      vlSection('2. Impugnação ao mérito'),
      `<p>${vlFill('PREENCHER')}</p>`,
      vlSection('3. Impugnação de documentos'),
      `<p>${vlFill('PREENCHER')}</p>`,
      vlSection('4. Provas e requerimentos'),
      `<p>Requer provas ${vlFill('documental/testemunhal/pericial')} e prosseguimento do feito.</p>`,
      vlSignature('Advogado(a)'),
    ]),
    metadata: {
      sections: [{ title: 'Réplica', help: 'Responda por itens, com base em prova e direito.' }],
      internalComments: ['Checar prazo de réplica', 'Avaliar saneamento e provas'],
      blocks: [{ id: 'b_rep', type: 'textBox', title: 'Pontos da réplica' }],
    },
  },
  {
    systemKey: 'CIVIL_MANIFESTACAO',
    title: 'MANIFESTAÇÃO',
    description: 'Manifestação genérica (sobre documentos/decisão/laudo/petição adversa).',
    tags: ['Cível', 'CPC', 'Manifestação', 'Sistema'],
    preferredStorage: 'WORD_ONLINE',
    content: vlWrap([
      vlTitle('MANIFESTAÇÃO'),
      vlSubtitle('Modelo genérico • Objetivo • Pronto para adaptação'),
      ...civilIntro(
        'PARTE',
        'PARTE CONTRÁRIA',
        ['Art. 9º/10 (contraditório)', 'Art. 435 (documento novo)', 'Art. 370 (poderes instrutórios)'],
        [
          'Indicar exatamente sobre o que se manifesta (ID/data)',
          'Pontos objetivos em bullets (sem repetição)',
          'Requerimentos claros (o que o juízo deve decidir/determinar)',
          'Anexos listados com finalidade',
          'Checagem de prazos e intimações',
        ],
      ),
      `<p><strong>Excelentíssimo(a) Senhor(a) Doutor(a) Juiz(a) de Direito</strong></p>`,
      `<p>${vlFill('PREENCHER: JUÍZO/VARA')}<br/><span style="color:#64748b;">Sugestão:</span> {{process.vars}} • {{process.district}}</p>`,
      `<hr/>`,
      `<p><strong>{{contact.name}}</strong>, vem apresentar <strong>MANIFESTAÇÃO</strong> sobre ${vlFill('PREENCHER: O QUE')}.</p>`,
      vlSection('1. Síntese'),
      `<p>${vlFill('PREENCHER')}</p>`,
      vlSection('2. Pontos objetivos'),
      `<ul><li>${vlFill('PREENCHER')}</li><li>${vlFill('PREENCHER')}</li><li>${vlFill('PREENCHER')}</li></ul>`,
      vlSection('3. Requerimentos'),
      `<p>${vlFill('PREENCHER')}</p>`,
      vlSignature('Advogado(a)'),
    ]),
    metadata: {
      sections: [{ title: 'Requerimentos', help: 'Diga exatamente o que o juízo deve determinar.' }],
      internalComments: ['Referenciar ID do documento/decisão e datas.'],
      blocks: [{ id: 'b_man', type: 'list', title: 'Pontos' }],
    },
  },
  {
    systemKey: 'CIVIL_IMPUGNACAO',
    title: 'IMPUGNAÇÃO',
    description: 'Impugnação genérica (documentos/planilha/laudo/alegações) com tabela de pontos impugnados.',
    tags: ['Cível', 'CPC', 'Impugnação', 'Sistema'],
    preferredStorage: 'WORD_ONLINE',
    content: vlWrap([
      vlTitle('IMPUGNAÇÃO'),
      vlSubtitle('Modelo genérico • Impugnação específica • Requerimentos claros'),
      ...civilIntro(
        'IMPUGNANTE',
        'IMPUGNADO',
        ['Art. 9º/10 (contraditório)', 'Art. 341 (impugnação específica)', 'Art. 434/435 (documentos)', 'Art. 373 (ônus da prova)'],
        [
          'Tabela “alegação x correção x prova” preenchida item a item',
          'Provas anexas correspondentes a cada impugnação',
          'Pedidos objetivos (desentranhar/desconsiderar/retificar/perícia)',
          'Diligências e intimações requeridas, se cabível',
          'Evitar alegações genéricas (risco de preclusão)',
        ],
      ),
      `<p><strong>Excelentíssimo(a) Senhor(a) Doutor(a) Juiz(a) de Direito</strong></p>`,
      `<p>${vlFill('PREENCHER: JUÍZO/VARA')}<br/><span style="color:#64748b;">Sugestão:</span> {{process.vars}} • {{process.district}}</p>`,
      `<hr/>`,
      `<p><strong>{{contact.name}}</strong>, vem apresentar <strong>IMPUGNAÇÃO</strong> a ${vlFill('PREENCHER: O QUE')} apresentado por <strong>{{opposing.name}}</strong>.</p>`,
      vlSection('1. Pontos impugnados (tabela)'),
      `<table style="width:100%; border-collapse:collapse; border:1px solid #E2E8F0; background:#FFFFFF; margin: 8px 0;">`,
      `<tr>`,
      `<th style="border:1px solid #E2E8F0; padding:8px; text-align:left; background:#F1F5F9;">Item</th>`,
      `<th style="border:1px solid #E2E8F0; padding:8px; text-align:left; background:#F1F5F9;">Alegação</th>`,
      `<th style="border:1px solid #E2E8F0; padding:8px; text-align:left; background:#F1F5F9;">Impugnação/Correção</th>`,
      `</tr>`,
      `<tr>`,
      `<td style="border:1px solid #E2E8F0; padding:8px;">1</td>`,
      `<td style="border:1px solid #E2E8F0; padding:8px;">${vlFill('PREENCHER')}</td>`,
      `<td style="border:1px solid #E2E8F0; padding:8px;">${vlFill('PREENCHER')}</td>`,
      `</tr>`,
      `</table>`,
      vlSection('2. Fundamentos'),
      `<p>${vlFill('PREENCHER')}</p>`,
      vlSection('3. Requerimentos'),
      `<p>${vlFill('PREENCHER')}</p>`,
      vlSignature('Advogado(a)'),
    ]),
    metadata: {
      sections: [{ title: 'Tabela', help: 'Alegação x correção x prova.' }],
      internalComments: ['Separar por itens.', 'Anexar prova para cada impugnação.'],
      blocks: [{ id: 'b_imp', type: 'table', title: 'Tabela de impugnação' }],
    },
  },
  {
    systemKey: 'CIVIL_JUNTADA_DOCUMENTOS',
    title: 'JUNTADA DE DOCUMENTOS',
    description: 'Petição de juntada de documentos com tabela de anexos e finalidade probatória.',
    tags: ['Cível', 'CPC', 'Juntada', 'Sistema'],
    preferredStorage: 'WORD_ONLINE',
    content: vlWrap([
      vlTitle('JUNTADA DE DOCUMENTOS'),
      vlSubtitle('Tabela de anexos • Finalidade probatória • Requerimentos'),
      ...civilIntro(
        'PARTE',
        'PARTE CONTRÁRIA',
        ['Art. 434/435 (documentos)', 'Art. 437 (contraditório sobre documento)', 'Art. 9º/10 (contraditório)'],
        [
          'Tabela de anexos preenchida (nome + finalidade)',
          'PDFs legíveis e na ordem correta',
          'Sem duplicidade e sem anexos desnecessários',
          'Pedido de juntada + ciência/intimação (se necessário)',
          'Referência aos fatos que cada documento prova',
        ],
      ),
      `<p><strong>Excelentíssimo(a) Senhor(a) Doutor(a) Juiz(a) de Direito</strong></p>`,
      `<p>${vlFill('PREENCHER: JUÍZO/VARA')}<br/><span style="color:#64748b;">Sugestão:</span> {{process.vars}} • {{process.district}}</p>`,
      `<hr/>`,
      `<p><strong>{{contact.name}}</strong>, vem requerer a <strong>JUNTADA</strong> dos documentos abaixo.</p>`,
      vlSection('1. Documentos anexos'),
      `<table style="width:100%; border-collapse:collapse; border:1px solid #E2E8F0; background:#FFFFFF; margin: 8px 0;">`,
      `<tr>`,
      `<th style="border:1px solid #E2E8F0; padding:8px; text-align:left; background:#F1F5F9;">#</th>`,
      `<th style="border:1px solid #E2E8F0; padding:8px; text-align:left; background:#F1F5F9;">Documento</th>`,
      `<th style="border:1px solid #E2E8F0; padding:8px; text-align:left; background:#F1F5F9;">Finalidade</th>`,
      `</tr>`,
      `<tr>`,
      `<td style="border:1px solid #E2E8F0; padding:8px;">1</td>`,
      `<td style="border:1px solid #E2E8F0; padding:8px;">${vlFill('PREENCHER')}</td>`,
      `<td style="border:1px solid #E2E8F0; padding:8px;">${vlFill('PREENCHER')}</td>`,
      `</tr>`,
      `</table>`,
      vlSection('2. Requerimentos'),
      `<p>Requer a juntada e consideração dos documentos para fins de prova, com intimações de praxe.</p>`,
      vlSignature('Advogado(a)'),
    ]),
    metadata: {
      sections: [{ title: 'Documentos', help: 'Liste anexos e vincule a um fato.' }],
      internalComments: ['Conferir legibilidade e ordem.', 'Evitar duplicidade.'],
      blocks: [{ id: 'b_docs', type: 'table', title: 'Tabela de anexos' }],
    },
  },
  {
    systemKey: 'CIVIL_ESPECIFICACAO_PROVAS',
    title: 'ESPECIFICAÇÃO DE PROVAS',
    description: 'Especificação de provas com checklist e detalhamento (documental, testemunhal, pericial, etc.).',
    tags: ['Cível', 'CPC', 'Provas', 'Sistema'],
    preferredStorage: 'WORD_ONLINE',
    content: vlWrap([
      vlTitle('ESPECIFICAÇÃO DE PROVAS'),
      vlSubtitle('Saneamento • Pontos controvertidos • Provas requeridas'),
      ...civilIntro(
        'PARTE',
        'PARTE CONTRÁRIA',
        ['Art. 357 (saneamento e organização do processo)', 'Art. 369 (meios de prova)', 'Art. 370 (poder instrutório)'],
        [
          'Pontos controvertidos listados (frases curtas)',
          'Meio de prova vinculado a cada ponto controvertido',
          'Rol de testemunhas/quesitos/assistente preparados (se cabível)',
          'Pedido de audiência/perícia bem definido',
          'Prazos e despacho de saneamento conferidos',
        ],
      ),
      `<p><strong>Excelentíssimo(a) Senhor(a) Doutor(a) Juiz(a) de Direito</strong></p>`,
      `<p>${vlFill('PREENCHER: JUÍZO/VARA')}<br/><span style="color:#64748b;">Sugestão:</span> {{process.vars}} • {{process.district}}</p>`,
      `<hr/>`,
      `<p><strong>{{contact.name}}</strong>, vem apresentar <strong>ESPECIFICAÇÃO DE PROVAS</strong>.</p>`,
      vlSection('1. Pontos controvertidos'),
      `<ol><li>${vlFill('PREENCHER')}</li><li>${vlFill('PREENCHER')}</li></ol>`,
      vlSection('2. Provas requeridas (checklist)'),
      `<table style="width:100%; border-collapse:collapse; border:1px solid #E2E8F0; background:#FFFFFF;">`,
      `<tr><td style="border:1px solid #E2E8F0; padding:10px; width:50%;">☐ Documental suplementar<br/>☐ Depoimento pessoal<br/>☐ Inspeção judicial</td>`,
      `<td style="border:1px solid #E2E8F0; padding:10px; width:50%;">☐ Testemunhal (rol)<br/>☐ Pericial (quesitos/assistente)<br/>☐ Prova técnica</td></tr>`,
      `</table>`,
      `<p style="margin-top: 10px;"><strong>Detalhamento:</strong> ${vlFill('PREENCHER')}</p>`,
      vlSection('3. Requerimentos'),
      `<p>Requer o deferimento das provas e a designação de ${vlFill('audiência/perícia')}.</p>`,
      vlSignature('Advogado(a)'),
    ]),
    metadata: {
      sections: [{ title: 'Provas', help: 'Especifique meio de prova e objetivo.' }],
      internalComments: ['Checar prazo.', 'Preparar rol/quesitos.'],
      blocks: [{ id: 'b_provas', type: 'checklist', title: 'Checklist de provas' }],
    },
  },
  {
    systemKey: 'CIVIL_ALEGACOES_FINAIS',
    title: 'ALEGAÇÕES FINAIS',
    description: 'Alegações finais (memoriais) com síntese, provas, direito e pedido final.',
    tags: ['Cível', 'CPC', 'Memoriais', 'Sistema'],
    preferredStorage: 'WORD_ONLINE',
    content: vlWrap([
      vlTitle('ALEGAÇÕES FINAIS'),
      vlSubtitle('Memoriais • Provas produzidas • Conclusão objetiva'),
      ...civilIntro(
        'PARTE',
        'PARTE CONTRÁRIA',
        ['Art. 364 (alegações finais/debates)', 'Art. 371 (valoração da prova)', 'Art. 85 (honorários)'],
        [
          'Síntese curta (sem recontar tudo)',
          'Provas produzidas destacadas e vinculadas à tese',
          'Pontos controvertidos enfrentados um a um',
          'Pedido final claro (procedência/improcedência)',
          'Sem contradições com as peças anteriores',
        ],
      ),
      `<p><strong>Excelentíssimo(a) Senhor(a) Doutor(a) Juiz(a) de Direito</strong></p>`,
      `<p>${vlFill('PREENCHER: JUÍZO/VARA')}<br/><span style="color:#64748b;">Sugestão:</span> {{process.vars}} • {{process.district}}</p>`,
      `<hr/>`,
      `<p><strong>{{contact.name}}</strong>, vem apresentar <strong>ALEGAÇÕES FINAIS</strong> (memoriais).</p>`,
      vlSection('1. Síntese'),
      `<p>${vlFill('PREENCHER')}</p>`,
      vlSection('2. Provas produzidas'),
      `<ul><li>${vlFill('PREENCHER')}</li><li>${vlFill('PREENCHER')}</li></ul>`,
      vlSection('3. Enquadramento jurídico'),
      `<p>${vlFill('PREENCHER')}</p>`,
      vlSection('4. Pedido final'),
      `<p>Requer ${vlFill('procedência/improcedência')} nos termos dos pedidos formulados, com custas e honorários.</p>`,
      vlSignature('Advogado(a)'),
    ]),
    metadata: {
      sections: [{ title: 'Provas', help: 'Vincule prova à tese, em bullets.' }],
      internalComments: ['Checar fato superveniente.', 'Conferir forma de apresentação.'],
      blocks: [{ id: 'b_mem', type: 'list', title: 'Pontos' }],
    },
  },
  {
    systemKey: 'CIVIL_HABILITACAO',
    title: 'HABILITAÇÃO',
    description: 'Habilitação/Sucessão processual (CPC, art. 110).',
    tags: ['Cível', 'CPC', 'Habilitação', 'Sistema'],
    preferredStorage: 'WORD_ONLINE',
    content: vlWrap([
      vlTitle('HABILITAÇÃO / SUCESSÃO PROCESSUAL'),
      vlSubtitle('Substituição de parte • Habilitação de sucessores • CPC (art. 110)'),
      ...civilIntro(
        'INTERESSADO',
        'PARTE CONTRÁRIA',
        ['Art. 110 (sucessão processual)', 'Art. 313, I (suspensão por morte)', 'Art. 9º/10 (contraditório)'],
        [
          'Fato gerador comprovado (certidão/contrato)',
          'Legitimidade demonstrada (herdeiros/cessionário)',
          'Documentos essenciais listados e anexados',
          'Pedido de substituição no polo + intimações futuras',
          'Regularidade de representação (procuração) conferida',
        ],
      ),
      `<p><strong>Excelentíssimo(a) Senhor(a) Doutor(a) Juiz(a) de Direito</strong></p>`,
      `<p>${vlFill('PREENCHER: JUÍZO/VARA')}<br/><span style="color:#64748b;">Sugestão:</span> {{process.vars}} • {{process.district}}</p>`,
      `<hr/>`,
      `<p><strong>{{contact.name}}</strong>, vem requerer <strong>HABILITAÇÃO</strong> nos presentes autos.</p>`,
      vlSection('1. Fato gerador'),
      `<p>${vlFill('PREENCHER: óbito/cessão/sub-rogação e prova')}</p>`,
      vlSection('2. Legitimidade e documentos'),
      `<p>${vlFill('PREENCHER')}</p>`,
      vlSection('3. Pedido'),
      `<p>Requer a habilitação e substituição processual, com atualização do polo e intimações em nome de ${vlFill('PREENCHER: patrono/OAB')}.</p>`,
      vlSignature('Advogado(a)'),
    ]),
    metadata: {
      sections: [{ title: 'Documentos', help: 'Listar documentos que provam legitimidade.' }],
      internalComments: ['Checar inventário/arrolamento.'],
      blocks: [{ id: 'b_hab', type: 'list', title: 'Documentos' }],
    },
  },
  {
    systemKey: 'CIVIL_PETICAO_ACORDO',
    title: 'PETIÇÃO DE ACORDO',
    description: 'Petição de acordo para homologação judicial, com cláusulas essenciais, prazos e multa.',
    tags: ['Cível', 'CPC', 'Acordo', 'Sistema'],
    preferredStorage: 'WORD_ONLINE',
    content: vlWrap([
      vlTitle('PETIÇÃO DE ACORDO'),
      vlSubtitle('Homologação • Obrigações • Prazos • Multa'),
      ...civilIntro(
        'PARTE 1',
        'PARTE 2',
        ['Art. 487, III, “b” (homologação)', 'Art. 515, II (título judicial)', 'Art. 922 (suspensão na execução, se aplicável)'],
        [
          'Objeto, valor e forma de pagamento definidos',
          'Cláusula de multa/juros por inadimplemento',
          'Quitação (total/parcial) bem descrita',
          'Dados de pagamento/PIX conferidos',
          'Pedido de homologação + suspensão/extinção coerente',
        ],
      ),
      `<p><strong>Excelentíssimo(a) Senhor(a) Doutor(a) Juiz(a) de Direito</strong></p>`,
      `<p>${vlFill('PREENCHER: JUÍZO/VARA')}<br/><span style="color:#64748b;">Sugestão:</span> {{process.vars}} • {{process.district}}</p>`,
      `<hr/>`,
      `<p><strong>{{contact.name}}</strong> e <strong>{{opposing.name}}</strong> informam que celebraram <strong>ACORDO</strong>, requerendo sua homologação.</p>`,
      vlSection('1. Termos (tabela)'),
      `<table style="width:100%; border-collapse:collapse; border:1px solid #E2E8F0; background:#FFFFFF; margin: 8px 0;">`,
      `<tr><th style="border:1px solid #E2E8F0; padding:8px; text-align:left; background:#F1F5F9;">Cláusula</th><th style="border:1px solid #E2E8F0; padding:8px; text-align:left; background:#F1F5F9;">Conteúdo</th></tr>`,
      `<tr><td style="border:1px solid #E2E8F0; padding:8px;">Objeto</td><td style="border:1px solid #E2E8F0; padding:8px;">${vlFill('PREENCHER')}</td></tr>`,
      `<tr><td style="border:1px solid #E2E8F0; padding:8px;">Valor</td><td style="border:1px solid #E2E8F0; padding:8px;">${vlFill('PREENCHER')}</td></tr>`,
      `<tr><td style="border:1px solid #E2E8F0; padding:8px;">Pagamento</td><td style="border:1px solid #E2E8F0; padding:8px;">${vlFill('PREENCHER: forma, datas, parcelas')}</td></tr>`,
      `<tr><td style="border:1px solid #E2E8F0; padding:8px;">Multa</td><td style="border:1px solid #E2E8F0; padding:8px;">${vlFill('PREENCHER')}</td></tr>`,
      `<tr><td style="border:1px solid #E2E8F0; padding:8px;">Quitação</td><td style="border:1px solid #E2E8F0; padding:8px;">${vlFill('PREENCHER')}</td></tr>`,
      `</table>`,
      vlSection('2. Requerimentos'),
      `<p>Requerem homologação; suspensão do feito até cumprimento; e ao final extinção (art. 487, III, “b”, CPC).</p>`,
      vlSignature('Advogado(a)'),
    ]),
    metadata: {
      sections: [
        { title: 'Termos', help: 'Objeto, valor, pagamento, multa e quitação.' },
        { title: 'Requerimentos', help: 'Homologação + suspensão + extinção após cumprimento.' },
      ],
      internalComments: ['Conferir poderes para transigir no mandato.', 'Checar custas remanescentes.'],
      blocks: [{ id: 'b_acordo', type: 'table', title: 'Cláusulas' }],
    },
  },
  {
    systemKey: 'CIVIL_EMBARGOS_DECLARACAO',
    title: 'EMBARGOS DE DECLARAÇÃO',
    description: 'Embargos de declaração por omissão/contradição/obscuridade/erro material (CPC, art. 1.022).',
    tags: ['Cível', 'CPC', 'Embargos de Declaração', 'Sistema'],
    preferredStorage: 'WORD_ONLINE',
    content: vlWrap([
      vlTitle('EMBARGOS DE DECLARAÇÃO'),
      vlSubtitle('CPC, art. 1.022 • Vícios • Pedido objetivo'),
      ...civilIntro(
        'EMBARGANTE',
        'EMBARGADO',
        ['Art. 1.022 (cabimento)', 'Art. 1.023 (prazo)', 'Art. 1.026 (multa por protelatório)'],
        [
          'Decisão/sentença identificada (data/ID/trecho)',
          'Vício indicado (omissão/contradição/obscuridade/erro material)',
          'Impacto do vício explicado objetivamente',
          'Pedido claro (integrar/clarear/corrigir)',
          'Tempestividade conferida (5 dias)',
        ],
      ),
      `<p><strong>Excelentíssimo(a) Senhor(a) Doutor(a) Juiz(a) de Direito</strong></p>`,
      `<p>${vlFill('PREENCHER: JUÍZO/VARA')}<br/><span style="color:#64748b;">Sugestão:</span> {{process.vars}} • {{process.district}}</p>`,
      `<hr/>`,
      `<p><strong>{{contact.name}}</strong>, vem opor <strong>EMBARGOS DE DECLARAÇÃO</strong> em face da decisão/sentença de ${vlFill('PREENCHER: DATA/ID')}, com fundamento no art. 1.022 do CPC.</p>`,
      vlSection('1. Cabimento (vício)'),
      `<table style="width:100%; border-collapse:collapse; border:1px solid #E2E8F0; background:#FFFFFF;">`,
      `<tr><td style="border:1px solid #E2E8F0; padding:10px; width:50%;">☐ Omissão<br/>☐ Contradição</td><td style="border:1px solid #E2E8F0; padding:10px; width:50%;">☐ Obscuridade<br/>☐ Erro material</td></tr>`,
      `</table>`,
      `<p style="margin-top: 10px;">${vlFill('PREENCHER: apontar vício e impacto')}</p>`,
      vlSection('2. Pedido'),
      `<p>Requer o provimento para sanar o vício e integrar o julgado, com ${vlFill('se cabível: efeitos infringentes')}.</p>`,
      vlSignature('Advogado(a)'),
    ]),
    metadata: {
      sections: [{ title: 'Vício', help: 'Aponte o vício do art. 1.022 com precisão.' }],
      internalComments: ['Checar prazo (5 dias).', 'Indicar trechos exatos.'],
      blocks: [{ id: 'b_1022', type: 'checklist', title: 'Vícios' }],
    },
  },
  {
    systemKey: 'CIVIL_CUMPRIMENTO_SENTENCA',
    title: 'CUMPRIMENTO DE SENTENÇA',
    description: 'Cumprimento de sentença (CPC, art. 523): memória de cálculo, intimação para pagamento e multa/honorários.',
    tags: ['Cível', 'CPC', 'Cumprimento de Sentença', 'Sistema'],
    preferredStorage: 'WORD_ONLINE',
    content: vlWrap([
      vlTitle('CUMPRIMENTO DE SENTENÇA'),
      vlSubtitle('CPC, art. 523 • Memória de cálculo • Intimação para pagamento'),
      ...civilIntro(
        'EXEQUENTE',
        'EXECUTADO',
        ['Art. 513 (cumprimento de sentença)', 'Art. 523 (prazo + multa/honorários)', 'Art. 524 (memória discriminada do cálculo)'],
        [
          'Título e trânsito em julgado/eficácia identificados',
          'Planilha (art. 524) anexada e conferida',
          'Pedido de intimação para pagamento em 15 dias (art. 523)',
          'Multa/honorários de 10% previstos no pedido',
          'Pedidos de constrição (Sisbajud/Renajud) preparados (se necessário)',
        ],
      ),
      `<p><strong>Excelentíssimo(a) Senhor(a) Doutor(a) Juiz(a) de Direito</strong></p>`,
      `<p>${vlFill('PREENCHER: JUÍZO/VARA')}<br/><span style="color:#64748b;">Sugestão:</span> {{process.vars}} • {{process.district}}</p>`,
      `<hr/>`,
      `<p><strong>{{contact.name}}</strong>, vem requerer o <strong>CUMPRIMENTO DE SENTENÇA</strong> em face de <strong>{{opposing.name}}</strong>.</p>`,
      vlSection('1. Título e exigibilidade'),
      `<p>${vlFill('PREENCHER: sentença/acórdão, trânsito, obrigação')}</p>`,
      vlSection('2. Memória de cálculo'),
      `<p>${vlFill('PREENCHER: planilha, índices, juros, data-base')}</p>`,
      `<p><strong>Valor atualizado:</strong> ${vlFill('PREENCHER')}</p>`,
      vlSection('3. Pedido (art. 523)'),
      `<ol>`,
      `<li>Intimação do executado para pagar em 15 dias.</li>`,
      `<li>Não havendo pagamento, multa de 10% e honorários de 10% (art. 523, §1º, CPC).</li>`,
      `<li>${vlFill('PREENCHER: constrição (Sisbajud/Renajud)')}</li>`,
      `</ol>`,
      vlSection('4. Dados para pagamento (se aplicável)'),
      `<p>${vlFill('PREENCHER')}</p>`,
      vlSignature('Advogado(a)'),
    ]),
    metadata: {
      sections: [{ title: 'Cálculo', help: 'Anexar planilha clara com data-base.' }],
      internalComments: ['Verificar rito conforme obrigação.', 'Anexar planilha.'],
      blocks: [{ id: 'b_523', type: 'textBox', title: 'Memória de cálculo' }],
    },
  },
  {
    systemKey: 'CIVIL_IMPUGNACAO_CUMPRIMENTO_SENTENCA',
    title: 'IMPUGNAÇÃO AO CUMPRIMENTO DE SENTENÇA',
    description: 'Impugnação ao cumprimento de sentença (CPC, art. 525) com checklist de matérias e excesso de execução.',
    tags: ['Cível', 'CPC', 'Impugnação', 'Cumprimento de Sentença', 'Sistema'],
    preferredStorage: 'WORD_ONLINE',
    content: vlWrap([
      vlTitle('IMPUGNAÇÃO AO CUMPRIMENTO DE SENTENÇA'),
      vlSubtitle('CPC, art. 525 • Matérias impugnáveis • Excesso de execução'),
      ...civilIntro(
        'EXECUTADO',
        'EXEQUENTE',
        ['Art. 525 (impugnação)', 'Art. 525, §5º (excesso de execução)', 'Art. 525, §6º (efeito suspensivo)'],
        [
          'Prazo de 15 dias conferido e contado corretamente',
          'Matérias impugnadas selecionadas e provadas',
          'Em excesso: planilha alternativa anexada',
          'Pedido de efeito suspensivo fundamentado (se cabível)',
          'Pedidos finais claros (redução/extinção/retificação)',
        ],
      ),
      `<p><strong>Excelentíssimo(a) Senhor(a) Doutor(a) Juiz(a) de Direito</strong></p>`,
      `<p>${vlFill('PREENCHER: JUÍZO/VARA')}<br/><span style="color:#64748b;">Sugestão:</span> {{process.vars}} • {{process.district}}</p>`,
      `<hr/>`,
      `<p><strong>{{contact.name}}</strong>, vem apresentar <strong>IMPUGNAÇÃO</strong> ao cumprimento promovido por <strong>{{opposing.name}}</strong>, com fundamento no art. 525 do CPC.</p>`,
      vlSection('1. Tempestividade e garantia'),
      `<p>${vlFill('PREENCHER')}</p>`,
      vlSection('2. Matérias (checklist)'),
      `<table style="width:100%; border-collapse:collapse; border:1px solid #E2E8F0; background:#FFFFFF;">`,
      `<tr><td style="border:1px solid #E2E8F0; padding:10px; width:50%;">☐ Inexequibilidade<br/>☐ Ilegitimidade<br/>☐ Inexigibilidade</td>`,
      `<td style="border:1px solid #E2E8F0; padding:10px; width:50%;">☐ Excesso<br/>☐ Compensação<br/>☐ Prescrição</td></tr>`,
      `</table>`,
      `<p style="margin-top:10px;">${vlFill('PREENCHER: fundamentos + planilha (se excesso)')}</p>`,
      vlSection('3. Pedidos'),
      `<ol><li>${vlFill('PREENCHER')}</li><li>${vlFill('PREENCHER: efeito suspensivo (se cabível)')}</li></ol>`,
      vlSignature('Advogado(a)'),
    ]),
    metadata: {
      sections: [{ title: 'Matérias', help: 'Selecione matérias cabíveis e prove.' }],
      internalComments: ['Checar prazo do art. 525.', 'Em excesso: planilha alternativa.'],
      blocks: [{ id: 'b_525', type: 'checklist', title: 'Matérias (art. 525)' }],
    },
  },
  {
    systemKey: 'CIVIL_INICIAL_EXECUCAO',
    title: 'INICIAL DE EXECUÇÃO',
    description: 'Execução de título extrajudicial (CPC, art. 784) com pedido de citação para pagar e penhora.',
    tags: ['Cível', 'CPC', 'Execução', 'Sistema'],
    preferredStorage: 'WORD_ONLINE',
    content: vlWrap([
      vlTitle('INICIAL DE EXECUÇÃO'),
      vlSubtitle('Título extrajudicial • CPC, art. 784 • Citação + penhora'),
      ...civilIntro(
        'EXEQUENTE',
        'EXECUTADO',
        ['Art. 784 (títulos executivos)', 'Art. 798 (requisitos da inicial)', 'Art. 829 (citação para pagar)', 'Art. 827 (honorários)'],
        [
          'Título completo anexado (todas as páginas)',
          'Planilha/atualização anexada (data-base)',
          'Pedido de citação para pagar em 3 dias (art. 829)',
          'Pedido de penhora/meios eletrônicos (Sisbajud/Renajud)',
          'Honorários iniciais (art. 827) previstos',
        ],
      ),
      `<p><strong>Excelentíssimo(a) Senhor(a) Doutor(a) Juiz(a) de Direito</strong></p>`,
      `<p>${vlFill('PREENCHER: JUÍZO/VARA')}<br/><span style="color:#64748b;">Sugestão:</span> {{process.vars}} • {{process.district}}</p>`,
      `<hr/>`,
      `<p><strong>{{contact.name}}</strong>, vem propor <strong>EXECUÇÃO DE TÍTULO EXTRAJUDICIAL</strong> em face de <strong>{{opposing.name}}</strong>.</p>`,
      vlSection('1. Título executivo'),
      `<p>${vlFill('PREENCHER: identificar título e anexar')}</p>`,
      vlSection('2. Débito e planilha'),
      `<p>${vlFill('PREENCHER')}</p>`,
      vlSection('3. Pedidos'),
      `<ol>`,
      `<li>Citação para pagar em 3 dias (art. 829, CPC) ou garantir o juízo.</li>`,
      `<li>${vlFill('PREENCHER: penhora e meios eletrônicos')}</li>`,
      `<li>Custas e honorários (art. 827, CPC).</li>`,
      `</ol>`,
      vlSignature('Advogado(a)'),
    ]),
    metadata: {
      sections: [{ title: 'Título', help: 'Liquidez, certeza e exigibilidade.' }],
      internalComments: ['Checar foro/competência.', 'Anexar planilha e título completo.'],
      blocks: [{ id: 'b_exec', type: 'textBox', title: 'Título/planilha' }],
    },
  },
  {
    systemKey: 'CIVIL_EMBARGOS_EXECUCAO',
    title: 'EMBARGOS À EXECUÇÃO',
    description: 'Embargos à execução (CPC, art. 914) com tempestividade, garantia, fundamentos e pedidos.',
    tags: ['Cível', 'CPC', 'Execução', 'Embargos', 'Sistema'],
    preferredStorage: 'WORD_ONLINE',
    content: vlWrap([
      vlTitle('EMBARGOS À EXECUÇÃO'),
      vlSubtitle('CPC, art. 914 • Defesa do executado'),
      ...civilIntro(
        'EMBARGANTE (executado)',
        'EMBARGADO (exequente)',
        ['Art. 914 (cabimento)', 'Art. 915 (prazo)', 'Art. 919 (efeito suspensivo)'],
        [
          'Tempestividade demonstrada (intimação/prazo)',
          'Garantia do juízo indicada (quando aplicável)',
          'Matérias organizadas por tópicos + prova correspondente',
          'Em excesso: planilha alternativa anexada',
          'Pedidos finais claros + efeito suspensivo (se cabível)',
        ],
      ),
      `<p><strong>Excelentíssimo(a) Senhor(a) Doutor(a) Juiz(a) de Direito</strong></p>`,
      `<p>${vlFill('PREENCHER: JUÍZO/VARA')}<br/><span style="color:#64748b;">Sugestão:</span> {{process.vars}} • {{process.district}}</p>`,
      `<hr/>`,
      `<p><strong>{{contact.name}}</strong>, vem opor <strong>EMBARGOS À EXECUÇÃO</strong> promovida por <strong>{{opposing.name}}</strong>, com fundamento no art. 914 do CPC.</p>`,
      vlSection('1. Tempestividade e garantia'),
      `<p>${vlFill('PREENCHER: prazo, penhora/depósito/garantia')}</p>`,
      vlSection('2. Fundamentos'),
      `<p>${vlFill('PREENCHER: nulidades, inexigibilidade, excesso, pagamento, compensação, etc.')}</p>`,
      vlSection('3. Pedidos'),
      `<ol><li>${vlFill('PREENCHER')}</li><li>${vlFill('PREENCHER: efeito suspensivo (se cabível)')}</li></ol>`,
      vlSignature('Advogado(a)'),
    ]),
    metadata: {
      sections: [{ title: 'Fundamentos', help: 'Organize por tópicos e com prova.' }],
      internalComments: ['Checar prazo e requisito de garantia.', 'Em excesso: anexar planilha alternativa.'],
      blocks: [{ id: 'b_emb', type: 'textBox', title: 'Excesso/planilha' }],
    },
  },
  {
    systemKey: 'CIVIL_EXCECAO_PRE_EXECUTIVIDADE',
    title: 'EXCEÇÃO DE PRÉ-EXECUTIVIDADE',
    description: 'Exceção de pré-executividade para matérias de ordem pública com prova pré-constituída, sem garantia do juízo.',
    tags: ['Cível', 'CPC', 'Execução', 'Pré-executividade', 'Sistema'],
    preferredStorage: 'WORD_ONLINE',
    content: vlWrap([
      vlTitle('EXCEÇÃO DE PRÉ-EXECUTIVIDADE'),
      vlSubtitle('Ordem pública • Prova pré-constituída • Sem garantia'),
      ...civilIntro(
        'EXECUTADO',
        'EXEQUENTE',
        ['Art. 803 (nulidades da execução)', 'Contraditório (art. 9º/10)', 'Jurisprudência (pré-executividade)'],
        [
          'Matéria de ordem pública claramente delimitada',
          'Prova pré-constituída anexada (sem dilação)',
          'Pedido de suspensão de atos constritivos (se urgente)',
          'Ataque pontual ao vício (sem discutir mérito probatório)',
          'Pedidos coerentes (extinção/nulidade/retificação)',
        ],
      ),
      `<p><strong>Excelentíssimo(a) Senhor(a) Doutor(a) Juiz(a) de Direito</strong></p>`,
      `<p>${vlFill('PREENCHER: JUÍZO/VARA')}<br/><span style="color:#64748b;">Sugestão:</span> {{process.vars}} • {{process.district}}</p>`,
      `<hr/>`,
      `<p><strong>{{contact.name}}</strong>, vem suscitar <strong>EXCEÇÃO DE PRÉ-EXECUTIVIDADE</strong> na execução promovida por <strong>{{opposing.name}}</strong>.</p>`,
      vlSection('1. Cabimento'),
      `<p>${vlFill('PREENCHER: matéria de ordem pública + prova pré-constituída')}</p>`,
      vlSection('2. Fundamentos'),
      `<p>${vlFill('PREENCHER: nulidade, prescrição, ilegitimidade, etc.')}</p>`,
      vlSection('3. Pedidos'),
      `<p>Requer o acolhimento para ${vlFill('extinguir/suspender')} a execução e demais cominações.</p>`,
      vlSignature('Advogado(a)'),
    ]),
    metadata: {
      sections: [{ title: 'Cabimento', help: 'Ordem pública + prova pré-constituída.' }],
      internalComments: ['Anexar prova documental pré-constituída.', 'Pedir suspensão de atos (se necessário).'],
      blocks: [{ id: 'b_pre', type: 'list', title: 'Provas anexas' }],
    },
  },
  {
    systemKey: 'CIVIL_RENUNCIA_MANDATO',
    title: 'RENÚNCIA DE MANDATO',
    description: 'Renúncia de mandato (CPC, art. 112) com comunicação ao cliente e requerimentos de anotação/intimação.',
    tags: ['Cível', 'CPC', 'Mandato', 'Renúncia', 'Sistema'],
    preferredStorage: 'WORD_ONLINE',
    content: vlWrap([
      vlTitle('RENÚNCIA DE MANDATO'),
      vlSubtitle('CPC, art. 112 • Comunicação ao cliente • Prazo de 10 dias'),
      ...civilIntro(
        'CLIENTE',
        'PARTE CONTRÁRIA',
        ['Art. 112 (renúncia do mandato)', 'Prazo de 10 dias (dever de atuação)', 'Comprovação de comunicação'],
        [
          'Comprovante de comunicação ao cliente anexado',
          'Data e meio de comunicação informados (e-mail/WhatsApp/AR)',
          'Pedido de anotação e intimação da parte após prazo',
          'Controle interno do prazo de 10 dias',
          'Checagem de poderes/andamentos pendentes antes de renunciar',
        ],
      ),
      `<p><strong>Excelentíssimo(a) Senhor(a) Doutor(a) Juiz(a) de Direito</strong></p>`,
      `<p>${vlFill('PREENCHER: JUÍZO/VARA')}<br/><span style="color:#64748b;">Sugestão:</span> {{process.vars}} • {{process.district}}</p>`,
      `<hr/>`,
      `<p><strong>{{user.name}}</strong>, advogado(a), informa a <strong>RENÚNCIA</strong> ao mandato outorgado por <strong>{{contact.name}}</strong>, nos termos do art. 112 do CPC.</p>`,
      vlSection('1. Comunicação ao mandante'),
      `<p>Comunicação enviada em ${vlFill('PREENCHER: DATA')}, por ${vlFill('PREENCHER: meio')}, conforme comprovante anexo.</p>`,
      vlSection('2. Requerimentos'),
      `<ol>`,
      `<li>Registro da renúncia e observância do prazo legal para regularização da representação.</li>`,
      `<li>${vlFill('PREENCHER: requerimentos específicos')}</li>`,
      `</ol>`,
      `<p style="margin-top: 18px;">${vlFill('ANEXAR: comprovante de comunicação ao cliente')}</p>`,
      vlSignature('Advogado(a)'),
    ]),
    metadata: {
      sections: [{ title: 'Comunicação', help: 'Anexar comprovante de comunicação ao mandante.' }],
      internalComments: ['CPC art. 112: manter-se por 10 dias após comunicação.'],
      blocks: [{ id: 'b_ren', type: 'list', title: 'Prova de comunicação' }],
    },
  },
  {
    systemKey: 'CIVIL_SUBSTABELECIMENTO',
    title: 'SUBSTABELECIMENTO',
    description: 'Substabelecimento (com ou sem reserva), com campos para advogado substabelecido e poderes.',
    tags: ['Cível', 'Mandato', 'Substabelecimento', 'Sistema'],
    preferredStorage: 'WORD_ONLINE',
    content: vlWrap([
      vlTitle('SUBSTABELECIMENTO'),
      vlSubtitle('Com/sem reserva • Poderes • Identificação do substabelecido'),
      ...civilIntro(
        'CLIENTE',
        'PARTE CONTRÁRIA',
        ['Definir com/sem reserva', 'Poderes específicos (se houver)', 'Juntar procuração quando necessário'],
        [
          'Tipo definido (com/sem reserva)',
          'Dados do substabelecido (nome/OAB) preenchidos',
          'Poderes específicos e limitações descritos',
          'Assinaturas conferidas (se exigidas)',
          'Peticionamento nos autos, se necessário',
        ],
      ),
      `<p><strong>SUBSTABELECENTE:</strong> {{user.name}} ${vlFill('PREENCHER OAB')}</p>`,
      `<p><strong>SUBSTABELECIDO:</strong> ${vlFill('PREENCHER: NOME')} – OAB ${vlFill('PREENCHER: OAB')}</p>`,
      `<p><strong>MANDANTE:</strong> {{contact.name}}, CPF/CNPJ {{contact.document}}</p>`,
      `<p><strong>PROCESSO:</strong> {{process.cnj}} • {{process.vars}} • {{process.district}}</p>`,
      `<hr/>`,
      vlSection('1. Cláusula'),
      `<p>O(a) substabelecente substabelece ${vlFill('COM ou SEM reserva de poderes')} os poderes do mandato, para atuação no processo acima identificado.</p>`,
      vlSection('2. Observações'),
      `<p>${vlFill('PREENCHER: poderes específicos, limitações, contato do substabelecido')}</p>`,
      `<p style="margin-top: 20px;">${vlFill('LOCAL')}, {{today.fullDate}}.</p>`,
      `<table style="width:100%; border-collapse:collapse; margin-top: 18px;">`,
      `<tr>`,
      `<td style="width:50%; text-align:center;">________________________________________<br/>{{user.name}}<br/>${vlFill('OAB')}</td>`,
      `<td style="width:50%; text-align:center;">________________________________________<br/>${vlFill('NOME SUBSTABELECIDO')}<br/>${vlFill('OAB')}</td>`,
      `</tr>`,
      `</table>`,
    ]),
    metadata: {
      sections: [{ title: 'Cláusula', help: 'Defina se é com ou sem reserva e quais poderes.' }],
      internalComments: ['Juntar procuração original se necessário.', 'Checar necessidade de peticionar nos autos.'],
      blocks: [{ id: 'b_subs', type: 'checklist', title: 'Com/sem reserva' }],
    },
  },
  {
    systemKey: 'CHA_CONTRATO_HONORARIOS',
    title: 'CHA: Contrato de honorários',
    description: 'Contrato de honorários advocatícios (modelo Visual Law) preparado para Word Online.',
    tags: ['Cível', 'Contrato', 'Honorários', 'Sistema'],
    preferredStorage: 'WORD_ONLINE',
    content: vlWrap([
      vlTitle('CONTRATO DE HONORÁRIOS ADVOCATÍCIOS'),
      vlSubtitle('CHA • Modelo Visual Law • Cláusulas essenciais + checklists'),
      vlCard(
        'Partes (variáveis automáticas)',
        [
          `<strong>Contratante:</strong> {{contact.name}} — CPF/CNPJ {{contact.document}}`,
          `<strong>Endereço:</strong> {{contact.address.full}}`,
          `<strong>Contratado(a):</strong> {{user.name}} — OAB {{user.oab}}`,
          `<strong>E-mail:</strong> {{user.email}}`,
        ],
        'info',
      ),
      vlCard(
        'Checklist rápido (antes de assinar)',
        [
          'Objeto e escopo definidos (judicial/consultivo/administrativo)',
          'Honorários fixos e/ou êxito preenchidos com clareza',
          'Forma de pagamento e vencimentos conferidos',
          'Regras de reembolso de despesas descritas',
          'Foro e assinatura das partes conferidos',
        ],
        'warn',
      ),
      vlSection('1. Objeto e escopo'),
      `<p>O presente contrato tem por objeto a prestação de serviços advocatícios consistentes em ${vlFill('PREENCHER: DESCREVER ESCOPO')}.</p>`,
      `<p><strong>Processo (se houver):</strong> {{process.cnj}} — {{process.vars}} — {{process.district}}</p>`,
      vlSection('2. Honorários'),
      `<p><strong>Honorários fixos:</strong> ${vlFill('PREENCHER: R$ / forma')}</p>`,
      `<p><strong>Honorários de êxito:</strong> ${vlFill('PREENCHER: % / base de cálculo / evento de êxito')}</p>`,
      `<p><strong>Honorários sucumbenciais:</strong> ${vlFill('PREENCHER: (se serão do advogado, conforme art. 85, CPC)')}</p>`,
      vlSection('3. Pagamento e inadimplemento'),
      `<p>${vlFill('PREENCHER: forma de pagamento, datas, parcelamento e multa por atraso')}</p>`,
      vlSection('4. Despesas e reembolsos'),
      `<p>${vlFill('PREENCHER: custas, diligências, deslocamentos, correios, cópias, certidões — regra de reembolso')}</p>`,
      vlSection('5. Rescisão e encerramento'),
      `<p>${vlFill('PREENCHER: hipóteses de rescisão, prestação de contas, devolução de documentos, honorários proporcionais')}</p>`,
      vlSection('6. Foro'),
      `<p>Fica eleito o foro da comarca de ${vlFill('PREENCHER: COMARCA')} para dirimir controvérsias deste contrato.</p>`,
      vlSection('7. Texto-base completo (com dados iniciais)'),
      `<p style="margin: 6px 0 10px 0;"><strong>CONTRATO DE PRESTAÇÃO DE SERVIÇOS ADVOCATÍCIOS</strong></p>`,
      `<p>Pelo presente instrumento particular de contrato de prestação de serviços advocatícios, de um lado:</p>`,
      `<p><strong>DAS PARTES</strong></p>`,
      `<p><strong>CONSTITUÍDO(S):</strong> XAVIER XAVIER ADVOGADOS, pessoa jurídica de direito privado, inscrita no CNPJ sob nº 58.361.863/0001-74, com sede na Rua da Bahia, 603, Loja 09, Centro, Belo Horizonte/MG, CEP 30160-010, e-mail: xxavieradvogados@gmail.com, chave Pix (CNPJ) nº 58.361.863/0001-74, neste ato por seu(s) representante(s) legal(is): EVANDRO GERALDO XAVIER, brasileiro, advogado, OAB/MG 158.592, telefone 31-2534-7575, celular 31-99981-1174, e-mail: evandro@conectionmg.com.br; e LEANDRO RIBEIRO XAVIER, brasileiro, advogado, OAB/MG 226.816, telefone 31-2534-7575, celular 31-97309-7037, e-mail: leandro.x@msn.com, doravante denominado(s) <strong>CONSTITUÍDO</strong>, e de outro lado:</p>`,
      `<p><strong>CONSTITUINTE(S) (Pessoa Física):</strong> <strong>{{contact.name}}</strong>, nacionalidade {{contact.pf.nationality}}, estado civil {{contact.pf.civilStatus}}, profissão {{contact.pf.profession}}, inscrito(a) no CPF nº {{contact.pf.cpf}}, RG nº {{contact.pf.rg}}, residente e domiciliado(a) em {{contact.address.full}}, e-mail {{contact.email}}, data de nascimento {{contact.pf.birthDate}}, filiação: {{contact.pf.fatherName}} e {{contact.pf.motherName}}, doravante denominado(a) <strong>CONSTITUINTE</strong>.</p>`,
      `<p><strong>CONSTITUINTE(S) (Pessoa Jurídica):</strong> <strong>{{contact.pj.companyName}}</strong> (ou {{contact.name}}), pessoa jurídica inscrita no CNPJ nº {{contact.pj.cnpj}}, inscrição estadual nº {{contact.pj.stateRegistration}}, com sede em {{contact.address.full}}, e-mail {{contact.email}}, doravante denominada <strong>CONSTITUINTE</strong>.</p>`,
      `<p><strong>CONTRÁRIO(S)/PARTE ADVERSA (se houver):</strong> {{opposing.name}} — CPF/CNPJ {{opposing.document}} — endereço {{opposing.address.full}} — e-mail {{opposing.email}}.</p>`,
      `<p><strong>Processo (se houver):</strong> {{process.cnj}} — {{process.vars}} — {{process.district}}/{{process.uf}} — <strong>Valor:</strong> {{process.value}}</p>`,
      `<p><strong>DO OBJETO / VALORES / OBSERVAÇÕES</strong></p>`,
      `<p>${vlFill('PREENCHER: observações do caso (comarca, valor da causa, fase, pedidos, urgência etc.)')}</p>`,
      `<p><strong>FATOS:</strong> ${vlFill('PREENCHER: detalhar claramente o que aconteceu')}</p>`,
      `<p><strong>OBJETO DO CONTRATO:</strong> ${vlFill('PREENCHER: definição detalhada sobre os serviços que serão prestados')}</p>`,
      `<p><strong>DOS HONORÁRIOS E CONDIÇÕES DE PAGAMENTO</strong></p>`,
      `<p>O CONSTITUINTE pagará ao CONSTITUÍDO os honorários abaixo (ajustar conforme o caso):</p>`,
      `<table style="width:100%; border-collapse:collapse; margin-top: 8px;">`,
      `<tr>`,
      `<th style="border: 1px solid #CBD5E1; padding: 8px; background: #F1F5F9; text-align:left;">Descrição</th>`,
      `<th style="border: 1px solid #CBD5E1; padding: 8px; background: #F1F5F9; text-align:left;">Valor</th>`,
      `<th style="border: 1px solid #CBD5E1; padding: 8px; background: #F1F5F9; text-align:left;">Vencimento</th>`,
      `</tr>`,
      `<tr>`,
      `<td style="border: 1px solid #CBD5E1; padding: 8px;">Honorários iniciais</td>`,
      `<td style="border: 1px solid #CBD5E1; padding: 8px;">${vlFill('PREENCHER: R$ XXX.000,00')}</td>`,
      `<td style="border: 1px solid #CBD5E1; padding: 8px;">Neste ato</td>`,
      `</tr>`,
      `<tr>`,
      `<td style="border: 1px solid #CBD5E1; padding: 8px;">Honorários mensais (se houver)</td>`,
      `<td style="border: 1px solid #CBD5E1; padding: 8px;">R$ 250,00 ${vlFill('AJUSTAR')}</td>`,
      `<td style="border: 1px solid #CBD5E1; padding: 8px;">Dia 15 — correção anual pelo ${vlFill('PREENCHER: índice (ex.: IGP-M/FGV)')}</td>`,
      `</tr>`,
      `<tr>`,
      `<td style="border: 1px solid #CBD5E1; padding: 8px;">Honorários de êxito</td>`,
      `<td style="border: 1px solid #CBD5E1; padding: 8px;">30% ${vlFill('AJUSTAR')}</td>`,
      `<td style="border: 1px solid #CBD5E1; padding: 8px;">Sobre todo o proveito econômico (valor bruto), por sentença, acordo ou qualquer benefício obtido</td>`,
      `</tr>`,
      `</table>`,
      `<p>Pagará ao CONSTITUÍDO sobre o valor bruto recebido em caso de êxito, seja por sentença, acordo ou qualquer outro benefício econômico obtido em favor do CONSTITUINTE.</p>`,
      `<p><strong>Multa por atraso no pagamento:</strong> em caso de atraso no pagamento dos honorários, o CONSTITUINTE pagará multa de 10% (dez por cento) sobre o valor devido, acrescido de juros de mora de 1% (um por cento) ao mês e atualização monetária com base no IGP-M/FGV (ou ${vlFill('PREENCHER: outro índice')}).</p>`,
      `<p><strong>Despesas extras:</strong> todas as despesas processuais, como custas judiciais, fotocópias, autenticações, locomoção, hospedagem, alimentação e outras, deverão ser custeadas pelo CONSTITUINTE, podendo ser solicitadas antecipadamente, com prestação de contas posterior.</p>`,
      `<p><strong>DAS OBRIGAÇÕES DO CONSTITUÍDO</strong></p>`,
      `<ul style="margin: 6px 0 0 18px;">`,
      `<li>Prestar seus serviços advocatícios com honestidade, zelo e diligência, em conformidade com o Código de Ética e Disciplina da OAB e com o Estatuto da Advocacia (Lei nº 8.906/94).</li>`,
      `<li>Informar ao CONSTITUINTE sobre o andamento do processo sempre que solicitado, até a segunda instância, salvo pactuação posterior para outros recursos.</li>`,
      `<li>Praticar todos os atos necessários à defesa dos interesses do CONSTITUINTE perante órgãos públicos, repartições, tribunais e estabelecimentos particulares, conforme especificado no instrumento de procuração.</li>`,
      `</ul>`,
      `<p><strong>DAS OBRIGAÇÕES DO CONSTITUINTE</strong></p>`,
      `<ul style="margin: 6px 0 0 18px;">`,
      `<li>Pagar os honorários e custas processuais nos prazos e condições estabelecidos neste contrato.</li>`,
      `<li>Fornecer ao CONSTITUÍDO todos os documentos e informações necessárias à boa instrução do processo, dentro dos prazos estabelecidos.</li>`,
      `<li>Informar imediatamente ao CONSTITUÍDO qualquer mudança de endereço, telefone ou e-mail.</li>`,
      `<li>Cumprir fielmente todas as suas obrigações, sob pena de rescisão do contrato e revogação da procuração, caso haja ocultação de informações ou má-fé.</li>`,
      `</ul>`,
      `<p><strong>DA SUCUMBÊNCIA</strong></p>`,
      `<p>Os honorários sucumbenciais, caso sejam fixados em favor do CONSTITUÍDO, pertencerão exclusivamente a este, sem prejuízo dos honorários convencionais já ajustados com o CONSTITUINTE.</p>`,
      `<p><strong>DA VIGÊNCIA</strong></p>`,
      `<p>Este contrato entra em vigor na data de sua assinatura e será válido até a conclusão de todos os atos necessários ao término do processo ou do último recurso, caso haja interesse das partes.</p>`,
      `<p><strong>DA RESCISÃO E REVOGAÇÃO DO MANDATO</strong></p>`,
      `<p>O presente contrato poderá ser rescindido de pleno direito: (i) por acordo entre as partes; (ii) pela revogação do mandato pelo CONSTITUINTE, sem culpa do CONSTITUÍDO; (iii) pelo não prosseguimento da ação por circunstância alheia à vontade do CONSTITUÍDO. Em caso de rescisão sem culpa do CONSTITUÍDO, os honorários pactuados serão cobrados integralmente, conforme o caso concreto.</p>`,
      `<p><strong>DA REPRESENTAÇÃO</strong></p>`,
      `<p>O CONSTITUÍDO poderá designar outro(s) advogado(s) para representá-lo em qualquer ato processual, caso julgue necessário, sem prejuízo à defesa dos interesses do CONSTITUINTE.</p>`,
      `<p><strong>DO FORO</strong></p>`,
      `<p>As partes elegem o Foro de {{process.district}}/{{process.uf}} (ou ${vlFill('PREENCHER: COMARCA/UF')}) para dirimir quaisquer questões oriundas deste contrato, renunciando a qualquer outro, por mais privilegiado que seja.</p>`,
      `<p>E por estarem assim justos e contratados, assinam o presente instrumento em 02 (duas) vias de igual teor e forma, na presença de 02 (duas) testemunhas.</p>`,
      `<p><strong>TESTEMUNHAS:</strong></p>`,
      `<table style="width:100%; border-collapse:collapse; margin-top: 10px;">`,
      `<tr>`,
      `<td style="width:50%; padding: 8px; vertical-align:top; border: 1px solid #E2E8F0;">`,
      `<p style="margin:0 0 10px 0;">Ass.: ________________________________________</p>`,
      `<p style="margin:0;">NOME: ${vlFill('PREENCHER')}</p>`,
      `<p style="margin:0;">CPF: ${vlFill('PREENCHER')}</p>`,
      `</td>`,
      `<td style="width:50%; padding: 8px; vertical-align:top; border: 1px solid #E2E8F0;">`,
      `<p style="margin:0 0 10px 0;">Ass.: ________________________________________</p>`,
      `<p style="margin:0;">NOME: ${vlFill('PREENCHER')}</p>`,
      `<p style="margin:0;">CPF: ${vlFill('PREENCHER')}</p>`,
      `</td>`,
      `</tr>`,
      `</table>`,
      `<p style="margin-top: 20px;">${vlFill('LOCAL')}, {{today.fullDate}}.</p>`,
      `<table style="width:100%; border-collapse:collapse; margin-top: 18px;">`,
      `<tr>`,
      `<td style="width:50%; text-align:center;">________________________________________<br/>{{contact.name}}<br/>${vlFill('CPF/CNPJ')}</td>`,
      `<td style="width:50%; text-align:center;">________________________________________<br/>{{user.name}}<br/>OAB: {{user.oab}}</td>`,
      `</tr>`,
      `</table>`,
      `<hr style="margin: 22px 0 14px 0; border: 0; border-top: 1px solid #e2e8f0;" />`,
      vlSection('ANEXO I — PROCURAÇÃO'),
      `<p><strong>OUTORGADO(S):</strong> EVANDRO GERALDO XAVIER, brasileiro, advogado, OAB/MG 158.592, Escritório situado à Rua da Bahia, 603, loja 07, Centro, CEP 30160-010, Belo Horizonte/MG, Telefone 31-2534-7575, celular 31-99981-1174, e-mail: evandro@conectionmg.com.br; e LEANDRO RIBEIRO XAVIER, brasileiro, advogado, OAB/MG 226.816, Escritório situado à Rua da Bahia, 603, loja 07, Centro, CEP 30160-010, Belo Horizonte/MG, Telefone 31-2534-7575, celular 31-97309-7037, e-mail: leandro.x@msn.com.</p>`,
      `<p><strong>OUTORGANTE(S):</strong> {{contact.name}}, nacionalidade {{contact.pf.nationality}}, estado civil {{contact.pf.civilStatus}}, profissão {{contact.pf.profession}}, inscrito(a) no CPF nº {{contact.pf.cpf}}, RG nº {{contact.pf.rg}}, residente e domiciliado(a) em {{contact.address.full}}, e-mail {{contact.email}}, data de nascimento {{contact.pf.birthDate}}, filiação: {{contact.pf.fatherName}} e {{contact.pf.motherName}}.</p>`,
      `<p><strong>PODERES:</strong> O(s) outorgante(s) nomeia(m) os outorgados seus procuradores, conferindo-lhes os poderes da cláusula "ad judicia" e "ad extra", conjunta ou separadamente, para representá-lo(s) em juízo ou fora dele, outorgando-lhes ainda os especiais poderes para receber citação, de concordar, acordar, confessar, discordar, desistir, transigir, firmar compromissos, reconhecer a procedência do pedido, renunciar ao direito sobre o qual se funda a ação, receber, dar quitação, executar e fazer cumprir decisões e títulos judiciais e extrajudiciais, receber valores e levantar alvarás judiciais extraídos em nome do outorgante, requerer falências e concordatas, imputar a terceiros, em nome dos outorgantes, fatos descritos como crimes, arguir exceções de suspeição, firmar compromisso e declarar hipossuficiência econômica, constituir preposto, substabelecer com ou sem reserva os poderes conferidos pelo presente mandato. Declara ainda ciência de que o levantamento de créditos decorrentes de precatório ou RPV somente poderá ser efetivado mediante alvará judicial.</p>`,
      `<p><strong>PODERES ESPECÍFICOS:</strong> ${vlFill('PREENCHER: atuar em inventários/áreas especiais (opcional)')}</p>`,
      `<p style="margin-top: 18px;">{{process.district}}/{{process.uf}}, {{today.fullDate}}.</p>`,
      `<p style="margin-top: 18px;">________________________________________<br/>{{contact.name}}</p>`,
      `<hr style="margin: 22px 0 14px 0; border: 0; border-top: 1px solid #e2e8f0;" />`,
      vlSection('ANEXO II — DECLARAÇÃO DE HIPOSSUFICIÊNCIA'),
      `<p><strong>DECLARANTE(S):</strong> {{contact.name}}, nacionalidade {{contact.pf.nationality}}, estado civil {{contact.pf.civilStatus}}, profissão {{contact.pf.profession}}, inscrito(a) no CPF nº {{contact.pf.cpf}}, RG nº {{contact.pf.rg}}, residente e domiciliado(a) em {{contact.address.full}}, e-mail {{contact.email}}.</p>`,
      `<p>Venho através desta requerer a gratuidade de justiça, uma vez que necessito de acesso à justiça e por não haver condição financeira para arcar com as custas e despesas processuais, sem prejuízo do sustento próprio e familiar.</p>`,
      `<p>Amparado no art. 5º, inc. LXXIV da Constituição Federal e nas disposições da Lei nº 13.105/2015, requerer a Vossa Excelência a concessão do benefício da gratuidade da justiça, uma vez que se encontra impossibilitado(a) de prover as custas do processo e os honorários de advogado, sem prejuízo do sustento próprio e da família.</p>`,
      `<p><strong>Nestes termos, Pede Deferimento.</strong></p>`,
      `<p style="margin-top: 18px;">{{process.district}}/{{process.uf}}, {{today.fullDate}}.</p>`,
      `<p style="margin-top: 18px;">________________________________________<br/>{{contact.name}}</p>`,
    ]),
    metadata: {
      sections: [
        { title: 'Objeto', help: 'Descrever o escopo com o máximo de precisão (o que inclui e o que não inclui).' },
        { title: 'Honorários', help: 'Separar fixo x êxito e definir base de cálculo e gatilhos.' },
      ],
      internalComments: ['Confirmar poderes e limites do mandato.', 'Conferir se haverá cláusula de confidencialidade/LGPD.'],
      blocks: [{ id: 'b_cha', type: 'subtitle', title: 'Contrato de Honorários' }],
    },
  },
  {
    systemKey: 'CCV_COMPRA_VENDA_IMOVEL',
    title: 'CCV: Compra e Venda de Imóveis',
    description: 'Contrato de compra e venda de imóvel (modelo Visual Law) preparado para Word Online.',
    tags: ['Cível', 'Contrato', 'Imóvel', 'Compra e Venda', 'Sistema'],
    preferredStorage: 'WORD_ONLINE',
    content: vlWrap([
      vlTitle('CONTRATO DE COMPRA E VENDA DE IMÓVEL'),
      vlSubtitle('CCV • Modelo Visual Law • Cláusulas essenciais + checklist documental'),
      vlCard(
        'Partes (variáveis automáticas)',
        [
          `<strong>Comprador(a):</strong> {{contact.name}} — CPF/CNPJ {{contact.document}}`,
          `<strong>Endereço:</strong> {{contact.address.full}}`,
          `<strong>Vendedor(a):</strong> {{opposing.name}} — CPF/CNPJ {{opposing.document}}`,
          `<strong>Endereço:</strong> {{opposing.address.full}}`,
        ],
        'info',
      ),
      vlCard(
        'Checklist documental (antes de assinar)',
        [
          'Matrícula atualizada (inteiro teor)',
          'Certidões do imóvel (ônus/reipersecutórias)',
          'Certidões do vendedor (cíveis/fiscais/trabalhistas, conforme caso)',
          'IPTU/Condomínio em dia (comprovantes)',
          'Forma de pagamento e condições de imissão na posse conferidas',
        ],
        'warn',
      ),
      vlSection('1. Objeto — identificação do imóvel'),
      `<p>O(a) VENDEDOR(a) vende ao(à) COMPRADOR(a) o imóvel: ${vlFill('PREENCHER: ENDEREÇO COMPLETO')}, matrícula nº ${vlFill('PREENCHER: MATRÍCULA')} do Cartório ${vlFill('PREENCHER: CARTÓRIO/COMARCA')}.</p>`,
      vlSection('2. Preço e pagamento'),
      `<p><strong>Preço:</strong> ${vlFill('PREENCHER: R$')}</p>`,
      `<p><strong>Sinal/arras:</strong> ${vlFill('PREENCHER: R$ / data / condição')}</p>`,
      `<p><strong>Parcelas:</strong> ${vlFill('PREENCHER: quantidade, valores, vencimentos, correção/juros')}</p>`,
      vlSection('3. Posse, entrega de chaves e imissão'),
      `<p>${vlFill('PREENCHER: data/condição de entrega, estado de conservação, vistoria')}</p>`,
      vlSection('4. Obrigações, tributos e despesas'),
      `<p>${vlFill('PREENCHER: ITBI, escritura, registro, taxas cartorárias, IPTU, condomínio — quem paga o quê')}</p>`,
      vlSection('5. Declarações e garantias'),
      `<p>${vlFill('PREENCHER: inexistência de ônus, evicção, pendências e regularidade documental')}</p>`,
      vlSection('6. Multa e rescisão'),
      `<p>${vlFill('PREENCHER: multa por inadimplemento, rescisão, devolução de valores, retenções')}</p>`,
      vlSection('7. Foro'),
      `<p>Fica eleito o foro da comarca de ${vlFill('PREENCHER: COMARCA')} para dirimir controvérsias.</p>`,
      `<p style="margin-top: 20px;">${vlFill('LOCAL')}, {{today.fullDate}}.</p>`,
      `<table style="width:100%; border-collapse:collapse; margin-top: 18px;">`,
      `<tr>`,
      `<td style="width:50%; text-align:center;">________________________________________<br/>{{contact.name}}<br/>${vlFill('COMPRADOR(A)')}</td>`,
      `<td style="width:50%; text-align:center;">________________________________________<br/>{{opposing.name}}<br/>${vlFill('VENDEDOR(A)')}</td>`,
      `</tr>`,
      `</table>`,
      `<p style="margin-top: 18px;"><strong>Testemunhas:</strong> ${vlFill('PREENCHER NOME/CPF/ASSINATURA (2)')}</p>`,
    ]),
    metadata: {
      sections: [
        { title: 'Imóvel', help: 'Matrícula e identificação devem estar idênticas ao registro.' },
        { title: 'Pagamento', help: 'Descrever sinal, parcelas, vencimentos e correção com precisão.' },
      ],
      internalComments: ['Checar regime de bens/anuência do cônjuge (se aplicável).', 'Conferir cláusula de arras e prazos.'],
      blocks: [{ id: 'b_ccv', type: 'subtitle', title: 'Compra e Venda' }],
    },
  },
  {
    systemKey: 'NEJ_NOTIFICACAO_EXTRAJUDICIAL',
    title: 'NEJ: Notificação Extra Judicial',
    description: 'Notificação extrajudicial com identificação das partes, prazo e advertências.',
    tags: ['Cível', 'Notificação', 'Extrajudicial', 'Sistema'],
    preferredStorage: 'WORD_ONLINE',
    content: vlWrap([
      vlTitle('NOTIFICAÇÃO EXTRAJUDICIAL'),
      vlSubtitle('NEJ • Modelo Visual Law • Prazo + advertência + anexos'),
      vlCard(
        'Identificação (variáveis automáticas)',
        [
          `<strong>Notificante:</strong> {{contact.name}} — CPF/CNPJ {{contact.document}} — {{contact.address.full}}`,
          `<strong>Notificado(a):</strong> {{opposing.name}} — CPF/CNPJ {{opposing.document}} — {{opposing.address.full}}`,
          `<strong>Processo (se houver):</strong> {{process.cnj}}`,
        ],
        'info',
      ),
      vlCard(
        'Checklist (antes de enviar)',
        [
          'Fatos descritos com datas e documentos',
          'Prazo objetivo definido (dias corridos/úteis)',
          'Meio de envio definido (AR/e-mail/WhatsApp/cartório)',
          'Advertência proporcional e sem excesso',
          'Anexos listados e organizados',
        ],
        'warn',
      ),
      vlSection('1. Assunto'),
      `<p>${vlFill('PREENCHER: ASSUNTO/OBJETO DA NOTIFICAÇÃO')}</p>`,
      vlSection('2. Exposição dos fatos'),
      `<p>${vlFill('PREENCHER: fatos, datas, obrigações, tentativas anteriores de solução')}</p>`,
      vlSection('3. Notificação e prazo'),
      `<p>Fica o(a) NOTIFICADO(a) cientificado(a) e <strong>NOTIFICADO(a)</strong> para, no prazo de ${vlFill('PREENCHER: X DIAS')}, ${vlFill('PREENCHER: cumprir obrigação / cessar conduta / responder formalmente')}.</p>`,
      vlSection('4. Advertência'),
      `<p>O não atendimento importará na adoção das medidas cabíveis, inclusive ${vlFill('PREENCHER: ação judicial / execução / comunicação a órgãos')}, sem prejuízo de perdas e danos.</p>`,
      vlSection('5. Anexos'),
      `<p>${vlFill('PREENCHER: listar documentos anexados')}</p>`,
      `<p style="margin-top: 20px;">${vlFill('LOCAL')}, {{today.fullDate}}.</p>`,
      `<p style="margin-top: 22px;">________________________________________</p>`,
      `<p style="margin: 0;"><strong>{{user.name}}</strong></p>`,
      `<p style="margin: 0;">OAB: {{user.oab}} ${vlFill('PREENCHER OAB SE NECESSÁRIO')}</p>`,
    ]),
    metadata: {
      sections: [
        { title: 'Fatos', help: 'Descreva com datas e referencie documentos.' },
        { title: 'Prazo', help: 'Defina prazo e forma de comprovar o cumprimento.' },
      ],
      internalComments: ['Checar linguagem e proporcionalidade da advertência.', 'Escolher meio de envio com prova de recebimento.'],
      blocks: [{ id: 'b_nej', type: 'subtitle', title: 'Notificação Extrajudicial' }],
    },
  },
  {
    systemKey: 'CONVOCACAO_TESTEMUNHAS',
    title: 'Convocação de testemunhas',
    description: 'Carta/convocação para comparecimento de testemunha em audiência, com orientações e dados do processo.',
    tags: ['Cível', 'Audiência', 'Testemunha', 'Sistema'],
    preferredStorage: 'WORD_ONLINE',
    content: vlWrap([
      vlTitle('CONVOCAÇÃO DE TESTEMUNHA'),
      vlSubtitle('Modelo para comunicação e orientação de comparecimento'),
      vlCard(
        'Dados (variáveis automáticas)',
        [
          `<strong>Testemunha:</strong> {{contact.name}} — CPF/CNPJ {{contact.document}}`,
          `<strong>Contato:</strong> {{contact.phone}} / {{contact.whatsapp}}`,
          `<strong>Processo:</strong> {{process.cnj}} — {{process.vars}} — {{process.district}}`,
        ],
        'info',
      ),
      vlCard(
        'Checklist (preencher antes de enviar)',
        [
          'Data e horário da audiência',
          'Local/forma (presencial/virtual) + link/sala (se houver)',
          'Documento de identificação exigido',
          'Orientações sobre pontualidade e conduta',
          'Forma de confirmação de presença',
        ],
        'warn',
      ),
      vlSection('1. Convocação'),
      `<p>Prezado(a) <strong>{{contact.name}}</strong>,</p>`,
      `<p>Solicitamos o comparecimento como <strong>testemunha</strong> na audiência do processo indicado, a realizar-se em ${vlFill('PREENCHER: DATA')} às ${vlFill('PREENCHER: HORÁRIO')}.</p>`,
      `<p><strong>Local/forma:</strong> ${vlFill('PREENCHER: endereço / plataforma / link / sala')}</p>`,
      vlSection('2. Orientações'),
      `<ul>`,
      `<li>Levar documento oficial com foto.</li>`,
      `<li>Chegar com antecedência mínima de ${vlFill('PREENCHER: X MINUTOS')}.</li>`,
      `<li>${vlFill('PREENCHER: orientações específicas (virtual: conexão/câmera/áudio)')}</li>`,
      `</ul>`,
      vlSection('3. Confirmação'),
      `<p>Confirme presença pelo contato ${vlFill('PREENCHER: TELEFONE/WHATSAPP/E-MAIL')} até ${vlFill('PREENCHER: PRAZO')}.</p>`,
      `<p style="margin-top: 20px;">${vlFill('LOCAL')}, {{today.fullDate}}.</p>`,
      `<p style="margin-top: 22px;">________________________________________</p>`,
      `<p style="margin: 0;"><strong>{{user.name}}</strong></p>`,
      `<p style="margin: 0;">OAB: {{user.oab}} ${vlFill('PREENCHER OAB SE NECESSÁRIO')}</p>`,
    ]),
    metadata: {
      sections: [
        { title: 'Convocação', help: 'Sempre preencher data, horário e local/forma (presencial/virtual).' },
        { title: 'Orientações', help: 'Inclua link/sala e instruções para audiência virtual, se houver.' },
      ],
      internalComments: ['Evitar linguagem de intimação judicial (quando for apenas convite).', 'Confirmar se a testemunha foi arrolada e se há necessidade de intimação.'],
      blocks: [{ id: 'b_test', type: 'subtitle', title: 'Convocação de Testemunha' }],
    },
  },
];
