export { Dashboard } from './Dashboard';
export * from './Placeholders';
export { Login } from './Login';
export * from './contacts';
export { Register } from './Register';
export { Settings } from './Settings';
export { Library } from './Library';
export { UsersPage } from './Users';
export { Financial } from './Financial';
export { Processes } from './processes/Processes';
export { Agenda } from './Agenda';
export { ProductsList } from './products/ProductsList';
export { ForgotPassword } from './ForgotPassword';
export { ResetPassword } from './ResetPassword';
export { Atendimento } from './atendimento/atendimento';
export { ProcessConfig } from './processes/ProcessConfig';
export { ProcessTasks } from './processes/ProcessTasks';
export { ProposalsPage } from './inventory/ProposalsPage';
export { PurchasesPage } from './inventory/PurchasesPage';
export { FiscalPage } from './inventory/FiscalPage';
export { PaymentConditions } from './PaymentConditions';
export { InventoryDashboard } from './inventory/InventoryDashboard';
export { Inventory } from './inventory/Inventory';
