export * from './Dashboard';
export { ChatPage as Chat } from './ChatPage';
export * from './Placeholders';
export * from './Login';
export * from './contacts';
export * from './Register';
export * from './Settings';
export * from './Library';
export * from './Users';
export * from './Financial';
export { Processes } from './processes/Processes';
export { Agenda } from './Agenda';
export { ProductsList } from './products/ProductsList';
export * from './ForgotPassword';
export * from './ResetPassword';
export { AtendimentoPage } from './atendimento/atendimento-v2';
export { Kanban } from './Kanban';
export { ProcessConfig } from './processes/ProcessConfig';
export { ProcessTasks } from './processes/ProcessTasks';
export { ProposalsPage } from './inventory/ProposalsPage';
export { PurchasesPage } from './inventory/PurchasesPage';
export { FiscalPage } from './inventory/FiscalPage';
export { PaymentConditions } from './PaymentConditions';
export { InventoryDashboard } from './inventory/InventoryDashboard';
export { Inventory } from './inventory/Inventory';
