export * from './Dashboard';
export { ChatPage as Chat } from './ChatPage';
export * from './Placeholders';
export * from './Login';
export * from './contacts';
export * from './Register';
export * from './Settings';
export * from './Documents';
export * from './Users';
export * from './Financial';
export { ProcessList as Processes } from './processes/ProcessList';
export { Agenda } from './Agenda';
export { ProductsList } from './products/ProductsList';
export * from './ForgotPassword';
export * from './ResetPassword';
